function [fitresult, gof] = dodgeSurfaceFit( set, base )
% DODGESURFACEFIT(SET, BASE)
%  Input:
%      set : a data set structure generated by parseChatLog
%      base : structure containing base stat information
%
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2012 15:15:46

%% unpack data set
baseAgi = base.agi;
baseDodge = base.dodge;
bonusAgi = set.agi - base.agi;
preDodge = set.preDodge;
postDodge = set.postDodge;
a2d = base.agi2dodge;
vs = base.vs;
df = base.df;
k = base.k;

bonusDodge = bonusAgi*a2d+preDodge;

%% Fit: 'untitled fit 1'.
% [xInput, yInput, zOutput] = prepareSurfaceData( bonusAgi, preDodge, postDodge);
xInput = bonusDodge; zOutput = postDodge;
fitType=[ int2str(baseDodge) '+x/(x*' num2str(df) '*vs+' int2str(k) ')'];

% Set up fittype and options.
ft = fittype( fitType , 'indep', 'x', 'depend', 'z' );
opts = fitoptions( ft );
opts.DiffMinChange = 1e-012;
opts.Display = 'Off';
opts.Lower = [0.00664];
opts.MaxFunEvals = 60000;
opts.MaxIter = 40000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.00665];
opts.TolFun = 1e-012;
opts.TolX = 1e-012;
opts.Upper = [0.00666];

% Fit model to data.
[fitresult, gof] = fit( xInput, zOutput, ft, opts );

% Create a figure for the plots.
figure( 1 );

% Plot fit with data.
h = plot( fitresult, xInput, zOutput );
legend( h, 'fit', 'postDodge vs. bonusDodge', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusDodge' );
ylabel( 'postDodge' );
grid on

% Plot residuals.
figure(2)
h = plot( fitresult, xInput, zOutput, 'Style', 'Residual' );
legend( h, 'fit residuals', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusDodge' );
zlabel( 'postDodge' );
grid on
% view( -57.5, 56 );


