function [fitresult, gof] = dodgeSurfaceFit( set, base )
% DODGESURFACEFIT(SET, BASE)
%  Input:
%      set : a data set structure generated by parseChatLog
%      base : structure containing base stat information
%
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2012 15:15:46

%% unpack data set
baseAgi = base.agi;
baseDodge = base.dodge;
bonusAgi = set.agi - base.agi;
preDodge = set.preDodge;
postDodge = set.postDodge;
a2d = base.agi2dodge;

%% Fit: 'untitled fit 1'.
[xInput, yInput, zOutput] = prepareSurfaceData( bonusAgi, preDodge, postDodge);
fitType=[ int2str(baseDodge) '+' int2str(baseAgi) '/' num2str(a2d,'%f') '+(x/' num2str(a2d,'%f') '+y)/((x/' num2str(a2d,'%f') '+y)/C+k)'];

% Set up fittype and options.
ft = fittype( fitType , 'indep', {'x', 'y'}, 'depend', 'z' );
opts = fitoptions( ft );
opts.DiffMinChange = 1e-012;
opts.Display = 'Off';
opts.Lower = [50 0.7];
opts.MaxFunEvals = 60000;
opts.MaxIter = 40000;
opts.Robust = 'Bisquare';
opts.StartPoint = [499.1 1.422];
opts.TolFun = 1e-012;
opts.TolX = 1e-012;
opts.Upper = [520 1.5];

% Fit model to data.
[fitresult, gof] = fit( [xInput, yInput], zOutput, ft, opts );

% Create a figure for the plots.
figure( 1 );

% Plot fit with data.
h = plot( fitresult, [xInput, yInput], zOutput );
legend( h, 'fit', 'postParry vs. bonusStr, preParry', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusAgi' );
ylabel( 'preDodge' );
zlabel( 'postDodge' );
grid on

% Plot residuals.
figure(2)
h = plot( fitresult, [xInput, yInput], zOutput, 'Style', 'Residual' );
legend( h, 'fit residuals', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusAgi' );
ylabel( 'preDodge' );
zlabel( 'postDodge' );
grid on
view( -57.5, 56 );


