function [fitresult, gof] = parrySurfaceFit(str, predrparry, parry)
%CREATESURFACEFIT(STR,PREDRPARRY,PARRY)
%  Fit surface to data.
%
%  Data for 'untitled fit 1' fit:
%      X Input : str
%      Y Input : predrparry
%      Z Output: parry
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 27-Aug-2012 08:29:13


%% Fit: 'untitled fit 1'.
[xInput, yInput, zOutput] = prepareSurfaceData( str, predrparry, parry );

% Set up fittype and options.
ft = fittype( '1/(1/C+0.885/(x/243.6+y))', 'indep', {'x', 'y'}, 'depend', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [210];
opts.StartPoint = [236];
opts.Upper = [250];

% Fit model to data.
[fitresult, gof] = fit( [xInput, yInput], zOutput, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
plot( fitresult, [xInput, yInput], zOutput );
% Label axes
xlabel( 'str' );
ylabel( 'predrparry' );
zlabel( 'parry' );
grid on
view( -30.5, 20 );


