function [ Cstr kstr ] = printFitValues( fit, gof )
%PRINTFITVALUES displays the fit values generated by dodgeSurfaceFit or
%               parrySurfaceFit to high-precision 
%   

% extract interval information
cints=confint(fit);
fvals=coeffvalues(fit);

% error range
err=max(cints)-fvals;

% find num sig figs
lval = ceil(log10(fvals));
rval = floor(log10(err));

% form strings
for j=1:length(fvals)
    formatString = ['%' int2str(lval(j)) '.' int2str(1-rval(j)) 'f'];
    strings{j}=[ num2str(fvals(j),formatString) ' +/- ' num2str(err(j),formatString) ];
    
end

Cstr = [' C = ' strings{1}];
kstr = [' k = ' strings{2}];

disp(Cstr)
disp(kstr)
end

