function [ Cstr kstr ] = printFitValues( fit, gof )
%PRINTFITVALUES displays the fit values generated by dodgeSurfaceFit or
%               parrySurfaceFit to high-precision 
%   

% extract interval information
cints=confint(fit);
fvals=coeffvalues(fit);

% error range
err=max(cints)-fvals;

% find num sig figs
lval = ceil(log10(fvals));
rval = floor(log10(err));

% form strings
for j=1:length(fvals)
    if isnan(lval(j)) || isinf(lval(j))
        lval(j)=1;
    end
    if isnan(rval(j)) || isinf(rval(j))
        rval(j)=1;
    end
    formatString = ['%' int2str(lval(j)) '.' int2str(1-rval(j)) 'f'];
    strings{j}=[ num2str(fvals(j),formatString) ' +/- ' num2str(err(j),formatString) ];
    
end

Qstr = [' R = ' strings{1}];
HSstr = [' HS = ' strings{2}];
VSstr = [' VS = ' strings{3}];

disp(Qstr)
disp(HSstr)
disp(VSstr)
end

