%%% WARNING %%%
% This file is generated by make_gear_db.pl.  Do not edit it directly, as any
% changes will be overrun when the script is run again.  You should instead edit
% gear_db_head.m or gear_db_foot.m if you need to make changes to this output

%% Gear
%This file serves as a master gear database.

%To generate these entries, use make_gear_db.pl at command line: 
%  perl make_gear_db.pl --verbose > gear_db.m

%% Contribution from gear
%Item stats and effects are stored in the global databases "idb.iid", respectively "idb.sid".
%Items are referenced by IIDs (as can be found from the wowhead link), effects by SIDs.
%The databases are structure arrays with fields that correspond to the item's stats. The
%fields are initialized by the Sample Item below, which we've assigned an
%item number of 1.  All additional items can be added the way Broken
%Promise is in the section that follows.


%% Invoking Gear and the Equipped Gear Set

%The currently-equipped set is called the Equipped Gear Set, and stored in
%structure egs.  The fields of egs are identical to the fields of idb:
%egs.name       (item name)
%egs.atype      (logical : 1 for plate, 0 for the other armor types)
%egs.wtype      (axe/mac/swo; non-weapons are ignored)
%egs.ilvl       (item level)
%egs.tooldps    (tooltip dps, for referencing only)
%egs.swing      (base swing timer)
%egs.avgdmg 	(average base damage, for more precise calcs)
%egs.str
%egs.sta
%egs.agi
%egs.int
%egs.spi
%egs.ap
%egs.sp
%egs.hit
%egs.crit
%egs.exp
%egs.haste
%egs.mast       (mastery)
%egs.dodge
%egs.parry
%egs.barmor 	(base AC)
%egs.earmor 	(extra AC)
%egs.health 	(extra HP)
%egs.socket     'XYZ' string that labels sockets, RYBMP are valid chars
%egs.meta       boolean for meta, 0 for no meta, 1/2/3 for ?/?/?
%egs.sbstat     stat string for the socket bonus
%egs.sbval      value of socket bonus
%egs.istierP    (logical : [tier11P tier12P tier13P], undefined if not a tier set item)
%egs.istierR    (logical : [tier11P tier12P tier13P], undefined if not a tier set item)
%egs.isreforged (logical)

%However, egs only has 16 slots, corresponding to the 16 relevant slots on
%the paper doll. Shirt(18), Tabard (19) are ignored.
% HeadSlot          1
% NeckSlot          2
% ShoulderSlot      3
% BackSlot          4
% ChestSlot         5
% WristSlot         6
% HandsSlot         7
% WaistSlot         8
% LegsSlot          9
% FeetSlot          10
% Finger0Slot       11
% Finger1Slot       12
% Trinket0Slot      13
% Trinket1Slot      14
% MainHandSlot      15
% OffHandSlot       16

%Equipping an item is as simple as invoking the equip() function.  See the
%equip file for details about the syntax, but for a simple example we could
%equip Last Laugh in our main hand with either of the following lines:
% egs(15)=equip('Last Laugh');
% egs(15)=equip(40402);
%Note that the second one will execute much faster (direct reference rather
%than exhaustive search)

%To equip a particular set of items, one can make a gearset file that looks
%like this:
%
%egs(1)=equip('Sanctified Lightsworn Faceguard(Heroic)')
%egs(2)=equip('Bile-Encrusted Medallion')
%egs(3)=equip('Boneguard Commander's Pauldrons(Heroic)')
%
%and so forth.  

%TODO: Come up with a consistent way to handle items with identical names.
%They'll obviously have different item numbers, but the names should also
%be different so that the search function can return the proper stats.  For
%the moment, appending (Heroic) to heroic items will probably suffice, but
%there may be other situations we want to handle.



%% Initialize Item database
clear global idb;  %temporary fix for weird re-initialization issue
global idb
%initialize the substructure arrays
idb.iid=struct('name','Empty Slot', ...
               'atype',0, ...
               'wtype','swo', ...
               'ilvl',0, ...
               'tooldps',0, ...
               'swing',0, ...
               'avgdmg',0, ...
               'str',0, ...
               'sta',0, ...
               'agi',0, ...
               'int',0, ...
               'spi',0, ...
               'ap',0, ...
               'sp',0, ...
               'hit',0, ...
               'crit',0, ...
               'exp',0, ...
               'haste',0, ...
               'mast',0, ...
               'dodge',0, ...
               'parry',0, ...
               'barmor',0, ...
               'earmor',0, ...
               'health',0, ...
               'socket','', ...
               'meta',0, ...
               'sbstat','', ...
               'sbval',0, ...
               'istierP',[0 0 0],...
               'istierR',[0 0 0],...
               'isreforged',0, ...
               'procid',0);
           
idb.sid=struct('name','Empty Slot', ...
               'atype',0, ...
               'wtype','swo', ... 
               'ilvl',0, ...
               'tooldps',0, ...
               'swing',0, ...
               'avgdmg',0, ...
               'str',0, ...
               'sta',0, ...
               'agi',0, ...
               'int',0, ...
               'spi',0, ...
               'ap',0, ...
               'sp',0, ...
               'hit',0, ...
               'crit',0, ...
               'exp',0, ...
               'haste',0, ...
               'mast',0, ...
               'dodge',0, ...
               'parry',0, ...
               'barmor',0, ...
               'earmor',0, ...
               'health',0, ...
               'socket','', ...
               'meta',0, ...
               'sbstat','', ...
               'sbval',0, ...
               'istierP',[0 0 0],...
               'istierR',[0 0 0],...
               'isreforged',0, ...
               'procid',0);
        
%% Items

idb.iid(81456).name='Korjan Shoulders';
idb.iid(81456).ilvl=419;
idb.iid(81456).str=443;
idb.iid(81456).sta=665;
idb.iid(81456).hit=231;
idb.iid(81456).parry=333;
idb.iid(81456).barmor=3104;
idb.iid(81456).atype=1;
idb.iid(81456).isreforged=0;

idb.iid(81483).name='Korjan Warboots';
idb.iid(81483).ilvl=419;
idb.iid(81483).str=443;
idb.iid(81483).sta=665;
idb.iid(81483).mast=309;
idb.iid(81483).dodge=274;
idb.iid(81483).barmor=2845;
idb.iid(81483).atype=1;
idb.iid(81483).isreforged=0;

idb.iid(81492).name='Korjan Girdle';
idb.iid(81492).ilvl=419;
idb.iid(81492).str=443;
idb.iid(81492).sta=665;
idb.iid(81492).dodge=317;
idb.iid(81492).parry=259;
idb.iid(81492).barmor=2328;
idb.iid(81492).atype=1;
idb.iid(81492).isreforged=0;

idb.iid(81749).name='Thunderfoot Heavy Helm';
idb.iid(81749).ilvl=419;
idb.iid(81749).str=597;
idb.iid(81749).sta=895;
idb.iid(81749).hit=404;
idb.iid(81749).mast=388;
idb.iid(81749).barmor=3362;
idb.iid(81749).atype=1;
idb.iid(81749).isreforged=0;

idb.iid(81767).name='Thunderfoot Heavy Chestpiece';
idb.iid(81767).ilvl=419;
idb.iid(81767).str=597;
idb.iid(81767).sta=895;
idb.iid(81767).dodge=378;
idb.iid(81767).parry=410;
idb.iid(81767).barmor=4138;
idb.iid(81767).atype=1;
idb.iid(81767).isreforged=0;

idb.iid(81822).name='Shimmerback Band';
idb.iid(81822).ilvl=419;
idb.iid(81822).str=332;
idb.iid(81822).sta=498;
idb.iid(81822).mast=205;
idb.iid(81822).dodge=231;
idb.iid(81822).isreforged=0;

idb.iid(87351).name='Carapace Inlaid Drape';
idb.iid(87351).ilvl=440;
idb.iid(87351).str=404;
idb.iid(87351).sta=607;
idb.iid(87351).hit=237;
idb.iid(87351).parry=289;
idb.iid(87351).barmor=933;
idb.iid(87351).isreforged=0;

idb.iid(87356).name='Badge of the Amber Siege';
idb.iid(87356).ilvl=440;
idb.iid(87356).str=404;
idb.iid(87356).sta=607;
idb.iid(87356).mast=217;
idb.iid(87356).parry=300;
idb.iid(87356).isreforged=0;

idb.iid(87361).name='Martial Purification Gauntlets';
idb.iid(87361).ilvl=440;
idb.iid(87361).str=539;
idb.iid(87361).sta=808;
idb.iid(87361).mast=380;
idb.iid(87361).dodge=324;
idb.iid(87361).barmor=2821;
idb.iid(87361).atype=1;
idb.iid(87361).isreforged=0;

idb.iid(87362).name='Gauntlets of Righteous Conviction';
idb.iid(87362).ilvl=440;
idb.iid(87362).str=539;
idb.iid(87362).sta=808;
idb.iid(87362).exp=281;
idb.iid(87362).mast=405;
idb.iid(87362).barmor=2821;
idb.iid(87362).atype=1;
idb.iid(87362).isreforged=0;

idb.iid(87370).name='Waistguard of the Phalanx';
idb.iid(87370).ilvl=440;
idb.iid(87370).str=539;
idb.iid(87370).sta=808;
idb.iid(87370).mast=273;
idb.iid(87370).parry=410;
idb.iid(87370).barmor=2539;
idb.iid(87370).atype=1;
idb.iid(87370).isreforged=0;

idb.iid(87379).name='Runed Deathbone Chestplate';
idb.iid(87379).ilvl=440;
idb.iid(87379).str=726;
idb.iid(87379).sta=1088;
idb.iid(87379).mast=498;
idb.iid(87379).parry=460;
idb.iid(87379).barmor=4514;
idb.iid(87379).atype=1;
idb.iid(87379).isreforged=0;

idb.iid(75274).name='Zen Alchemist Stone';
idb.iid(75274).ilvl=450;
idb.iid(75274).mast=751;
idb.iid(75274).isreforged=0;

idb.iid(77530).name='Ghost Iron Dragonling';
idb.iid(77530).ilvl=450;
idb.iid(77530).mast=751;
idb.iid(77530).isreforged=0;

idb.iid(80927).name='Hive Protector\''s Gauntlets';
idb.iid(80927).ilvl=450;
idb.iid(80927).str=592;
idb.iid(80927).sta=888;
idb.iid(80927).hit=346;
idb.iid(80927).mast=423;
idb.iid(80927).barmor=2933;
idb.iid(80927).atype=1;
idb.iid(80927).isreforged=0;

idb.iid(82919).name='Masterwork Spiritguard Helm';
idb.iid(82919).ilvl=450;
idb.iid(82919).str=797;
idb.iid(82919).sta=1195;
idb.iid(82919).mast=492;
idb.iid(82919).dodge=555;
idb.iid(82919).barmor=3813;
idb.iid(82919).atype=1;
idb.iid(82919).isreforged=0;

idb.iid(82920).name='Masterwork Spiritguard Shoulders';
idb.iid(82920).ilvl=450;
idb.iid(82920).str=592;
idb.iid(82920).sta=888;
idb.iid(82920).mast=346;
idb.iid(82920).parry=423;
idb.iid(82920).barmor=3520;
idb.iid(82920).atype=1;
idb.iid(82920).isreforged=0;

idb.iid(82921).name='Masterwork Spiritguard Breastplate';
idb.iid(82921).ilvl=450;
idb.iid(82921).str=797;
idb.iid(82921).sta=1195;
idb.iid(82921).mast=539;
idb.iid(82921).dodge=518;
idb.iid(82921).barmor=4693;
idb.iid(82921).atype=1;
idb.iid(82921).isreforged=0;

idb.iid(82922).name='Masterwork Spiritguard Gauntlets';
idb.iid(82922).ilvl=450;
idb.iid(82922).str=592;
idb.iid(82922).sta=888;
idb.iid(82922).mast=401;
idb.iid(82922).parry=385;
idb.iid(82922).barmor=2933;
idb.iid(82922).atype=1;
idb.iid(82922).isreforged=0;

idb.iid(82923).name='Masterwork Spiritguard Legplates';
idb.iid(82923).ilvl=450;
idb.iid(82923).str=797;
idb.iid(82923).sta=1195;
idb.iid(82923).mast=492;
idb.iid(82923).dodge=555;
idb.iid(82923).barmor=4106;
idb.iid(82923).atype=1;
idb.iid(82923).isreforged=0;

idb.iid(82924).name='Masterwork Spiritguard Bracers';
idb.iid(82924).ilvl=450;
idb.iid(82924).str=444;
idb.iid(82924).sta=666;
idb.iid(82924).mast=300;
idb.iid(82924).parry=288;
idb.iid(82924).barmor=2053;
idb.iid(82924).atype=1;
idb.iid(82924).isreforged=0;

idb.iid(82925).name='Masterwork Spiritguard Boots';
idb.iid(82925).ilvl=450;
idb.iid(82925).str=592;
idb.iid(82925).sta=888;
idb.iid(82925).mast=375;
idb.iid(82925).dodge=406;
idb.iid(82925).barmor=3226;
idb.iid(82925).atype=1;
idb.iid(82925).isreforged=0;

idb.iid(82926).name='Masterwork Spiritguard Belt';
idb.iid(82926).ilvl=450;
idb.iid(82926).str=592;
idb.iid(82926).sta=888;
idb.iid(82926).mast=423;
idb.iid(82926).parry=346;
idb.iid(82926).barmor=2640;
idb.iid(82926).atype=1;
idb.iid(82926).isreforged=0;

idb.iid(82928).name='Masterwork Ghost-Forged Shoulders';
idb.iid(82928).ilvl=450;
idb.iid(82928).str=592;
idb.iid(82928).sta=888;
idb.iid(82928).hit=385;
idb.iid(82928).mast=401;
idb.iid(82928).barmor=3520;
idb.iid(82928).atype=1;
idb.iid(82928).isreforged=0;

idb.iid(82930).name='Masterwork Ghost-Forged Gauntlets';
idb.iid(82930).ilvl=450;
idb.iid(82930).str=592;
idb.iid(82930).sta=888;
idb.iid(82930).hit=375;
idb.iid(82930).mast=406;
idb.iid(82930).barmor=2933;
idb.iid(82930).atype=1;
idb.iid(82930).isreforged=0;

idb.iid(82932).name='Masterwork Ghost-Forged Bracers';
idb.iid(82932).ilvl=450;
idb.iid(82932).str=444;
idb.iid(82932).sta=666;
idb.iid(82932).hit=267;
idb.iid(82932).mast=313;
idb.iid(82932).barmor=2053;
idb.iid(82932).atype=1;
idb.iid(82932).isreforged=0;

idb.iid(82934).name='Masterwork Ghost-Forged Belt';
idb.iid(82934).ilvl=450;
idb.iid(82934).str=592;
idb.iid(82934).sta=888;
idb.iid(82934).hit=375;
idb.iid(82934).mast=406;
idb.iid(82934).barmor=2640;
idb.iid(82934).atype=1;
idb.iid(82934).isreforged=0;

idb.iid(82952).name='Contender\''s Spirit Shoulders';
idb.iid(82952).ilvl=450;
idb.iid(82952).str=592;
idb.iid(82952).sta=888;
idb.iid(82952).hit=365;
idb.iid(82952).mast=412;
idb.iid(82952).barmor=3520;
idb.iid(82952).atype=1;
idb.iid(82952).isreforged=0;

idb.iid(82954).name='Contender\''s Spirit Gauntlets';
idb.iid(82954).ilvl=450;
idb.iid(82954).str=592;
idb.iid(82954).sta=888;
idb.iid(82954).hit=356;
idb.iid(82954).mast=418;
idb.iid(82954).barmor=2933;
idb.iid(82954).atype=1;
idb.iid(82954).isreforged=0;

idb.iid(82956).name='Contender\''s Spirit Bracers';
idb.iid(82956).ilvl=450;
idb.iid(82956).str=444;
idb.iid(82956).sta=666;
idb.iid(82956).hit=313;
idb.iid(82956).mast=267;
idb.iid(82956).barmor=2053;
idb.iid(82956).atype=1;
idb.iid(82956).isreforged=0;

idb.iid(82958).name='Contender\''s Spirit Belt';
idb.iid(82958).ilvl=450;
idb.iid(82958).str=592;
idb.iid(82958).sta=888;
idb.iid(82958).hit=418;
idb.iid(82958).mast=356;
idb.iid(82958).barmor=2640;
idb.iid(82958).atype=1;
idb.iid(82958).isreforged=0;

idb.iid(83651).name='Temple Guardian Helm';
idb.iid(83651).ilvl=450;
idb.iid(83651).str=797;
idb.iid(83651).sta=1195;
idb.iid(83651).dodge=518;
idb.iid(83651).parry=539;
idb.iid(83651).barmor=3813;
idb.iid(83651).atype=1;
idb.iid(83651).isreforged=0;

idb.iid(83669).name='Temple Guardian Chestpiece';
idb.iid(83669).ilvl=450;
idb.iid(83669).str=797;
idb.iid(83669).sta=1195;
idb.iid(83669).hit=505;
idb.iid(83669).dodge=547;
idb.iid(83669).barmor=4693;
idb.iid(83669).atype=1;
idb.iid(83669).isreforged=0;

idb.iid(83729).name='Dreadling Signet';
idb.iid(83729).ilvl=450;
idb.iid(83729).str=444;
idb.iid(83729).sta=666;
idb.iid(83729).mast=288;
idb.iid(83729).dodge=300;
idb.iid(83729).isreforged=0;

idb.iid(83730).name='Dreadling Seal';
idb.iid(83730).ilvl=450;
idb.iid(83730).str=444;
idb.iid(83730).sta=666;
idb.iid(83730).exp=246;
idb.iid(83730).mast=326;
idb.iid(83730).isreforged=0;

idb.iid(83999).name='Bladesworn Shoulders';
idb.iid(83999).ilvl=450;
idb.iid(83999).str=592;
idb.iid(83999).sta=888;
idb.iid(83999).exp=328;
idb.iid(83999).mast=434;
idb.iid(83999).barmor=3520;
idb.iid(83999).atype=1;
idb.iid(83999).isreforged=0;

idb.iid(84026).name='Bladesworn Warboots';
idb.iid(84026).ilvl=450;
idb.iid(84026).str=592;
idb.iid(84026).sta=888;
idb.iid(84026).mast=401;
idb.iid(84026).dodge=385;
idb.iid(84026).barmor=3226;
idb.iid(84026).atype=1;
idb.iid(84026).isreforged=0;

idb.iid(84035).name='Bladesworn Girdle';
idb.iid(84035).ilvl=450;
idb.iid(84035).str=592;
idb.iid(84035).sta=888;
idb.iid(84035).mast=300;
idb.iid(84035).parry=450;
idb.iid(84035).barmor=2640;
idb.iid(84035).atype=1;
idb.iid(84035).isreforged=0;

idb.iid(85181).name='Iron Protector Talisman';
idb.iid(85181).ilvl=450;
idb.iid(85181).sta=1126;
idb.iid(85181).isreforged=0;

idb.iid(85186).name='Axebreaker Gauntlets';
idb.iid(85186).ilvl=450;
idb.iid(85186).str=450;
idb.iid(85186).sta=888;
idb.iid(85186).hit=300;
idb.iid(85186).parry=592;
idb.iid(85186).barmor=2933;
idb.iid(85186).atype=1;
idb.iid(85186).isreforged=0;

idb.iid(87427).name='Blade-Dulling Greatcloak';
idb.iid(87427).ilvl=450;
idb.iid(87427).str=444;
idb.iid(87427).sta=666;
idb.iid(87427).hit=232;
idb.iid(87427).dodge=333;
idb.iid(87427).barmor=970;
idb.iid(87427).isreforged=0;

idb.iid(87496).name='Daelo\''s Final Words';
idb.iid(87496).ilvl=450;
idb.iid(87496).hit=751;
idb.iid(87496).isreforged=0;

idb.iid(87501).name='Unbreakable Waistplate';
idb.iid(87501).ilvl=450;
idb.iid(87501).str=592;
idb.iid(87501).sta=888;
idb.iid(87501).hit=300;
idb.iid(87501).dodge=450;
idb.iid(87501).barmor=2640;
idb.iid(87501).atype=1;
idb.iid(87501).isreforged=0;

idb.iid(88995).name='Shado-Pan Dragon Gun';
idb.iid(88995).ilvl=450;
idb.iid(88995).isreforged=0;

idb.iid(81065).name='Bubble-Breaker Bracers (Heroic)';
idb.iid(81065).ilvl=463;
idb.iid(81065).str=501;
idb.iid(81065).sta=752;
idb.iid(81065).dodge=309;
idb.iid(81065).parry=349;
idb.iid(81065).barmor=2155;
idb.iid(81065).atype=1;
idb.iid(81065).isreforged=0;

idb.iid(81073).name='Stonestep Boots (Heroic)';
idb.iid(81073).ilvl=463;
idb.iid(81073).str=502;
idb.iid(81073).sta=1002;
idb.iid(81073).hit=349;
idb.iid(81073).dodge=668;
idb.iid(81073).barmor=3386;
idb.iid(81073).atype=1;
idb.iid(81073).isreforged=0;

idb.iid(81086).name='Sparkbreath Girdle (Heroic)';
idb.iid(81086).ilvl=463;
idb.iid(81086).str=668;
idb.iid(81086).sta=1002;
idb.iid(81086).dodge=338;
idb.iid(81086).parry=508;
idb.iid(81086).barmor=2771;
idb.iid(81086).atype=1;
idb.iid(81086).isreforged=0;

idb.iid(81096).name='Shield of Blind Hate (Heroic)';
idb.iid(81096).ilvl=463;
idb.iid(81096).str=501;
idb.iid(81096).sta=752;
idb.iid(81096).dodge=354;
idb.iid(81096).parry=301;
idb.iid(81096).barmor=15800;
idb.iid(81096).isreforged=0;

idb.iid(81100).name='Hive Protector\''s Gauntlets (Heroic)';
idb.iid(81100).ilvl=463;
idb.iid(81100).str=668;
idb.iid(81100).sta=1002;
idb.iid(81100).hit=391;
idb.iid(81100).mast=478;
idb.iid(81100).barmor=3079;
idb.iid(81100).atype=1;
idb.iid(81100).isreforged=0;

idb.iid(81101).name='Gauntlets of Resolute Fury (Heroic)';
idb.iid(81101).ilvl=463;
idb.iid(81101).str=668;
idb.iid(81101).sta=1002;
idb.iid(81101).mast=369;
idb.iid(81101).dodge=490;
idb.iid(81101).barmor=3079;
idb.iid(81101).atype=1;
idb.iid(81101).isreforged=0;

idb.iid(81124).name='Crystallized Droplet (Heroic)';
idb.iid(81124).ilvl=463;
idb.iid(81124).str=381;
idb.iid(81124).sta=752;
idb.iid(81124).hit=254;
idb.iid(81124).dodge=501;
idb.iid(81124).isreforged=0;

idb.iid(81133).name='Empty Fruit Barrel (Heroic)';
idb.iid(81133).ilvl=463;
idb.iid(81133).spi=847;
idb.iid(81133).isreforged=0;

idb.iid(81138).name='Carbonic Carbuncle (Heroic)';
idb.iid(81138).ilvl=463;
idb.iid(81138).str=847;
idb.iid(81138).isreforged=0;

idb.iid(81139).name='Lime-Rimmed Signet (Heroic)';
idb.iid(81139).ilvl=463;
idb.iid(81139).str=501;
idb.iid(81139).sta=752;
idb.iid(81139).mast=326;
idb.iid(81139).parry=339;
idb.iid(81139).isreforged=0;

idb.iid(81181).name='Heart of Fire (Heroic)';
idb.iid(81181).ilvl=463;
idb.iid(81181).mast=847;
idb.iid(81181).isreforged=0;

idb.iid(81187).name='Hateshatter Chestplate (Heroic)';
idb.iid(81187).ilvl=463;
idb.iid(81187).str=899;
idb.iid(81187).sta=1349;
idb.iid(81187).exp=512;
idb.iid(81187).mast=652;
idb.iid(81187).barmor=4926;
idb.iid(81187).atype=1;
idb.iid(81187).isreforged=0;

idb.iid(81230).name='Ri\''mok\''s Shattered Scale (Heroic)';
idb.iid(81230).ilvl=463;
idb.iid(81230).str=381;
idb.iid(81230).sta=752;
idb.iid(81230).exp=254;
idb.iid(81230).dodge=501;
idb.iid(81230).barmor=2155;
idb.iid(81230).atype=1;
idb.iid(81230).isreforged=0;

idb.iid(81233).name='Impervious Carapace (Heroic)';
idb.iid(81233).ilvl=463;
idb.iid(81233).str=381;
idb.iid(81233).sta=752;
idb.iid(81233).hit=254;
idb.iid(81233).parry=501;
idb.iid(81233).barmor=15800;
idb.iid(81233).isreforged=0;

idb.iid(81243).name='Iron Protector Talisman (Heroic)';
idb.iid(81243).ilvl=463;
idb.iid(81243).sta=1270;
idb.iid(81243).isreforged=0;

idb.iid(81248).name='Axebreaker Gauntlets (Heroic)';
idb.iid(81248).ilvl=463;
idb.iid(81248).str=508;
idb.iid(81248).sta=1002;
idb.iid(81248).hit=338;
idb.iid(81248).parry=668;
idb.iid(81248).barmor=3079;
idb.iid(81248).atype=1;
idb.iid(81248).isreforged=0;

idb.iid(81263).name='Flashfrozen Rosin Globule (Heroic)';
idb.iid(81263).ilvl=463;
idb.iid(81263).hit=847;
idb.iid(81263).isreforged=0;

idb.iid(81265).name='Flashing Steel Talisman (Heroic)';
idb.iid(81265).ilvl=463;
idb.iid(81265).hit=847;
idb.iid(81265).isreforged=0;

idb.iid(81268).name='Lessons of the Darkmaster (Heroic)';
idb.iid(81268).ilvl=463;
idb.iid(81268).exp=847;
idb.iid(81268).isreforged=0;

idb.iid(81270).name='Sap-Encrusted Legplates (Heroic)';
idb.iid(81270).ilvl=463;
idb.iid(81270).str=899;
idb.iid(81270).sta=1349;
idb.iid(81270).dodge=626;
idb.iid(81270).parry=555;
idb.iid(81270).barmor=4310;
idb.iid(81270).atype=1;
idb.iid(81270).isreforged=0;

idb.iid(81287).name='Spaulders of Immovable Stone (Heroic)';
idb.iid(81287).ilvl=463;
idb.iid(81287).str=668;
idb.iid(81287).sta=1002;
idb.iid(81287).dodge=478;
idb.iid(81287).parry=391;
idb.iid(81287).barmor=3694;
idb.iid(81287).atype=1;
idb.iid(81287).isreforged=0;

idb.iid(81567).name='Necklace of the Dark Blaze (Heroic)';
idb.iid(81567).ilvl=463;
idb.iid(81567).str=381;
idb.iid(81567).sta=752;
idb.iid(81567).exp=254;
idb.iid(81567).dodge=501;
idb.iid(81567).isreforged=0;

idb.iid(81568).name='Armsmaster\''s Sealed Locket (Heroic)';
idb.iid(81568).ilvl=463;
idb.iid(81568).str=501;
idb.iid(81568).sta=752;
idb.iid(81568).mast=262;
idb.iid(81568).parry=377;
idb.iid(81568).isreforged=0;

idb.iid(81571).name='Soulrender Greatcloak (Heroic)';
idb.iid(81571).ilvl=463;
idb.iid(81571).str=501;
idb.iid(81571).sta=752;
idb.iid(81571).dodge=349;
idb.iid(81571).parry=309;
idb.iid(81571).barmor=1018;
idb.iid(81571).isreforged=0;

idb.iid(81574).name='Helm of Rising Flame (Heroic)';
idb.iid(81574).ilvl=463;
idb.iid(81574).str=443;
idb.iid(81574).sta=1349;
idb.iid(81574).hit=316;
idb.iid(81574).parry=799;
idb.iid(81574).barmor=4002;
idb.iid(81574).socket='MY';
idb.iid(81574).sbstat='parry';
idb.iid(81574).sbval=180;
idb.iid(81574).atype=1;
idb.iid(81574).isreforged=0;

idb.iid(81687).name='Waistplate of Imminent Resurrection (Heroic)';
idb.iid(81687).ilvl=463;
idb.iid(81687).str=508;
idb.iid(81687).sta=1002;
idb.iid(81687).exp=338;
idb.iid(81687).dodge=668;
idb.iid(81687).barmor=2771;
idb.iid(81687).atype=1;
idb.iid(81687).isreforged=0;

idb.iid(81696).name='Canine Commander\''s Breastplate (Heroic)';
idb.iid(81696).ilvl=463;
idb.iid(81696).str=899;
idb.iid(81696).sta=1349;
idb.iid(81696).dodge=600;
idb.iid(81696).parry=600;
idb.iid(81696).barmor=4926;
idb.iid(81696).atype=1;
idb.iid(81696).isreforged=0;

idb.iid(82821).name='Breastplate of Wracking Souls (Heroic)';
idb.iid(82821).ilvl=463;
idb.iid(82821).str=683;
idb.iid(82821).sta=1349;
idb.iid(82821).exp=456;
idb.iid(82821).parry=899;
idb.iid(82821).barmor=4926;
idb.iid(82821).atype=1;
idb.iid(82821).isreforged=0;

idb.iid(82850).name='Phantasmal Drape (Heroic)';
idb.iid(82850).ilvl=463;
idb.iid(82850).str=381;
idb.iid(82850).sta=752;
idb.iid(82850).hit=254;
idb.iid(82850).dodge=501;
idb.iid(82850).barmor=1018;
idb.iid(82850).isreforged=0;

idb.iid(82852).name='Wraithplate Treads (Heroic)';
idb.iid(82852).ilvl=463;
idb.iid(82852).str=668;
idb.iid(82852).sta=1002;
idb.iid(82852).mast=458;
idb.iid(82852).parry=423;
idb.iid(82852).barmor=3386;
idb.iid(82852).atype=1;
idb.iid(82852).isreforged=0;

idb.iid(82857).name='Vigorsteel Spaulders (Heroic)';
idb.iid(82857).ilvl=463;
idb.iid(82857).str=508;
idb.iid(82857).sta=1002;
idb.iid(82857).hit=338;
idb.iid(82857).parry=668;
idb.iid(82857).barmor=3694;
idb.iid(82857).atype=1;
idb.iid(82857).isreforged=0;

idb.iid(81061).name='Ook\''s Hozen Slicer (Heroic)';
idb.iid(81061).wtype='swo';
idb.iid(81061).ilvl=463;
idb.iid(81061).tooldps=2436.7;
idb.iid(81061).swing=2.6;
idb.iid(81061).avgdmg=6335;
idb.iid(81061).str=385;
idb.iid(81061).sta=578;
idb.iid(81061).exp=279;
idb.iid(81061).mast=219;
idb.iid(81061).isreforged=0;

idb.iid(81577).name='Lightbreaker Greatsword (Heroic)';
idb.iid(81577).wtype='swo';
idb.iid(81577).ilvl=463;
idb.iid(81577).tooldps=3285.4;
idb.iid(81577).swing=3.6;
idb.iid(81577).avgdmg=11828;
idb.iid(81577).str=899;
idb.iid(81577).sta=1349;
idb.iid(81577).exp=456;
idb.iid(81577).mast=683;
idb.iid(81577).isreforged=0;

idb.iid(79327).name='Relic of Xuen';
idb.iid(79327).ilvl=476;
idb.iid(79327).str=956;
idb.iid(79327).isreforged=0;

idb.iid(79329).name='Relic of Nuzao';
idb.iid(79329).ilvl=476;
idb.iid(79329).isreforged=0;

idb.iid(79330).name='Relic of Chi Ji';
idb.iid(79330).ilvl=476;
idb.iid(79330).spi=956;
idb.iid(79330).isreforged=0;

idb.iid(86739).name='Beads of the Mogu\''shi (Raid Finder)';
idb.iid(86739).ilvl=476;
idb.iid(86739).str=430;
idb.iid(86739).sta=849;
idb.iid(86739).exp=287;
idb.iid(86739).dodge=566;
idb.iid(86739).isreforged=0;

idb.iid(86751).name='Bracers of Six Oxen (Raid Finder)';
idb.iid(86751).ilvl=476;
idb.iid(86751).str=566;
idb.iid(86751).sta=849;
idb.iid(86751).dodge=377;
idb.iid(86751).parry=377;
idb.iid(86751).barmor=2257;
idb.iid(86751).atype=1;
idb.iid(86751).isreforged=0;

idb.iid(86760).name='Sollerets of Spirit Splitting (Raid Finder)';
idb.iid(86760).ilvl=476;
idb.iid(86760).str=674;
idb.iid(86760).sta=1131;
idb.iid(86760).mast=470;
idb.iid(86760).dodge=446;
idb.iid(86760).barmor=3547;
idb.iid(86760).socket='Y';
idb.iid(86760).sbstat='dodge';
idb.iid(86760).sbval=60;
idb.iid(86760).atype=1;
idb.iid(86760).isreforged=0;

idb.iid(86771).name='Jade Charioteer Figurine (Raid Finder)';
idb.iid(86771).ilvl=476;
idb.iid(86771).str=956;
idb.iid(86771).isreforged=0;

idb.iid(86775).name='Jade Warlord Figurine (Raid Finder)';
idb.iid(86775).ilvl=476;
idb.iid(86775).sta=1434;
idb.iid(86775).isreforged=0;

idb.iid(86778).name='Steelskin, Qiang\''s Impervious Shield (Raid Finder)';
idb.iid(86778).ilvl=476;
idb.iid(86778).str=566;
idb.iid(86778).sta=849;
idb.iid(86778).dodge=368;
idb.iid(86778).parry=383;
idb.iid(86778).barmor=16546;
idb.iid(86778).isreforged=0;

idb.iid(86780).name='Shoulderguards of the Unflanked (Raid Finder)';
idb.iid(86780).ilvl=476;
idb.iid(86780).str=493;
idb.iid(86780).sta=1131;
idb.iid(86780).hit=342;
idb.iid(86780).parry=714;
idb.iid(86780).barmor=3869;
idb.iid(86780).socket='R';
idb.iid(86780).sbstat='sta';
idb.iid(86780).sbval=90;
idb.iid(86780).atype=1;
idb.iid(86780).isreforged=0;

idb.iid(86790).name='Vial of Dragon\''s Blood (Raid Finder)';
idb.iid(86790).ilvl=476;
idb.iid(86790).mast=956;
idb.iid(86790).isreforged=0;

idb.iid(86791).name='Bottle of Infinite Stars (Raid Finder)';
idb.iid(86791).ilvl=476;
idb.iid(86791).mast=956;
idb.iid(86791).isreforged=0;

idb.iid(86793).name='Star-Stealer Waistguard (Raid Finder)';
idb.iid(86793).ilvl=476;
idb.iid(86793).str=594;
idb.iid(86793).sta=1131;
idb.iid(86793).mast=361;
idb.iid(86793).dodge=459;
idb.iid(86793).barmor=2902;
idb.iid(86793).socket='YB';
idb.iid(86793).sbstat='dodge';
idb.iid(86793).sbval=120;
idb.iid(86793).atype=1;
idb.iid(86793).isreforged=0;

idb.iid(86805).name='Qin-xi\''s Polarizing Seal (Raid Finder)';
idb.iid(86805).ilvl=476;
idb.iid(86805).spi=956;
idb.iid(86805).isreforged=0;

idb.iid(86789).name='Elegion, the Fanged Crescent (Raid Finder)';
idb.iid(86789).wtype='axe';
idb.iid(86789).ilvl=476;
idb.iid(86789).tooldps=2750.5;
idb.iid(86789).swing=2.6;
idb.iid(86789).avgdmg=7151;
idb.iid(86789).str=435;
idb.iid(86789).sta=652;
idb.iid(86789).hit=303;
idb.iid(86789).exp=268;
idb.iid(86789).isreforged=0;

idb.iid(87545).name='Inelava, Spirit of Inebriation';
idb.iid(87545).wtype='axe';
idb.iid(87545).ilvl=476;
idb.iid(87545).tooldps=2750.5;
idb.iid(87545).swing=2.6;
idb.iid(87545).avgdmg=7151;
idb.iid(87545).str=435;
idb.iid(87545).sta=652;
idb.iid(87545).hit=220;
idb.iid(87545).mast=331;
idb.iid(87545).isreforged=0;

idb.iid(84806).name='Malevolent Gladiator\''s Cloak of Prowess';
idb.iid(84806).ilvl=483;
idb.iid(84806).str=604;
idb.iid(84806).sta=906;
idb.iid(84806).hit=353;
idb.iid(84806).mast=432;
idb.iid(84806).barmor=1092;
idb.iid(84806).isreforged=0;

idb.iid(84829).name='Malevolent Gladiator\''s Signet of Accuracy';
idb.iid(84829).ilvl=483;
idb.iid(84829).str=604;
idb.iid(84829).sta=906;
idb.iid(84829).hit=432;
idb.iid(84829).mast=353;
idb.iid(84829).isreforged=0;

idb.iid(84851).name='Malevolent Gladiator\''s Scaled Helm';
idb.iid(84851).ilvl=483;
idb.iid(84851).str=844;
idb.iid(84851).sta=1626;
idb.iid(84851).exp=723;
idb.iid(84851).mast=483;
idb.iid(84851).barmor=4293;
idb.iid(84851).socket='MR';
idb.iid(84851).atype=1;
idb.iid(84851).isreforged=0;

idb.iid(84931).name='Malevolent Gladiator\''s Medallion of Tenacity';
idb.iid(84931).ilvl=483;
idb.iid(84931).mast=1021;
idb.iid(84931).isreforged=0;

idb.iid(84932).name='Malevolent Gladiator\''s Medallion of Meditation';
idb.iid(84932).ilvl=483;
idb.iid(84932).spi=1021;
idb.iid(84932).isreforged=0;

idb.iid(84933).name='Malevolent Gladiator\''s Medallion of Meditation';
idb.iid(84933).ilvl=483;
idb.iid(84933).spi=1021;
idb.iid(84933).isreforged=0;

idb.iid(84937).name='Malevolent Gladiator\''s Insignia of Victory';
idb.iid(84937).ilvl=483;
idb.iid(84937).str=1021;
idb.iid(84937).isreforged=0;

idb.iid(84938).name='Malevolent Gladiator\''s Emblem of Tenacity';
idb.iid(84938).ilvl=483;
idb.iid(84938).mast=1021;
idb.iid(84938).isreforged=0;

idb.iid(84939).name='Malevolent Gladiator\''s Emblem of Meditation';
idb.iid(84939).ilvl=483;
idb.iid(84939).spi=1021;
idb.iid(84939).isreforged=0;

idb.iid(84942).name='Malevolent Gladiator\''s Badge of Victory';
idb.iid(84942).ilvl=483;
idb.iid(84942).str=1021;
idb.iid(84942).isreforged=0;

idb.iid(84945).name='Malevolent Gladiator\''s Medallion of Tenacity';
idb.iid(84945).ilvl=483;
idb.iid(84945).mast=1021;
idb.iid(84945).isreforged=0;

idb.iid(85044).name='Malevolent Gladiator\''s Scaled Helm';
idb.iid(85044).ilvl=483;
idb.iid(85044).str=844;
idb.iid(85044).sta=1626;
idb.iid(85044).exp=723;
idb.iid(85044).mast=483;
idb.iid(85044).barmor=4293;
idb.iid(85044).socket='MR';
idb.iid(85044).atype=1;
idb.iid(85044).isreforged=0;

idb.iid(86659).name='White Tiger Shoulderguards (Raid Finder)';
idb.iid(86659).ilvl=483;
idb.iid(86659).str=725;
idb.iid(86659).sta=1208;
idb.iid(86659).exp=408;
idb.iid(86659).mast=532;
idb.iid(86659).barmor=3963;
idb.iid(86659).socket='B';
idb.iid(86659).sbstat='sta';
idb.iid(86659).sbval=90;
idb.iid(86659).atype=1;
idb.iid(86659).isreforged=0;
idb.iid(86659).istierP=[1];

idb.iid(86660).name='White Tiger Legguards (Raid Finder)';
idb.iid(86660).ilvl=483;
idb.iid(86660).str=1004;
idb.iid(86660).sta=1626;
idb.iid(86660).mast=715;
idb.iid(86660).dodge=629;
idb.iid(86660).barmor=4623;
idb.iid(86660).socket='R';
idb.iid(86660).sbstat='sta';
idb.iid(86660).sbval=90;
idb.iid(86660).atype=1;
idb.iid(86660).isreforged=0;
idb.iid(86660).istierP=[1];

idb.iid(86661).name='White Tiger Faceguard (Raid Finder)';
idb.iid(86661).ilvl=483;
idb.iid(86661).str=584;
idb.iid(86661).sta=1626;
idb.iid(86661).exp=389;
idb.iid(86661).parry=1004;
idb.iid(86661).barmor=4293;
idb.iid(86661).socket='MB';
idb.iid(86661).sbstat='sta';
idb.iid(86661).sbval=270;
idb.iid(86661).atype=1;
idb.iid(86661).isreforged=0;
idb.iid(86661).istierP=[1];

idb.iid(86662).name='White Tiger Handguards (Raid Finder)';
idb.iid(86662).ilvl=483;
idb.iid(86662).str=612;
idb.iid(86662).sta=1208;
idb.iid(86662).hit=408;
idb.iid(86662).dodge=805;
idb.iid(86662).barmor=3302;
idb.iid(86662).atype=1;
idb.iid(86662).isreforged=0;
idb.iid(86662).istierP=[1];

idb.iid(86663).name='White Tiger Chestguard (Raid Finder)';
idb.iid(86663).ilvl=483;
idb.iid(86663).str=924;
idb.iid(86663).sta=1626;
idb.iid(86663).hit=463;
idb.iid(86663).parry=765;
idb.iid(86663).barmor=5284;
idb.iid(86663).socket='YY';
idb.iid(86663).sbstat='parry';
idb.iid(86663).sbval=120;
idb.iid(86663).atype=1;
idb.iid(86663).isreforged=0;
idb.iid(86663).istierP=[1];

idb.iid(86680).name='White Tiger Legplates (Raid Finder)';
idb.iid(86680).ilvl=483;
idb.iid(86680).str=1004;
idb.iid(86680).sta=1626;
idb.iid(86680).exp=594;
idb.iid(86680).mast=735;
idb.iid(86680).barmor=4623;
idb.iid(86680).socket='R';
idb.iid(86680).sbstat='str';
idb.iid(86680).sbval=60;
idb.iid(86680).atype=1;
idb.iid(86680).isreforged=0;
idb.iid(86680).istierR=[1];

idb.iid(86681).name='White Tiger Helmet (Raid Finder)';
idb.iid(86681).ilvl=483;
idb.iid(86681).str=844;
idb.iid(86681).sta=1626;
idb.iid(86681).hit=643;
idb.iid(86681).mast=563;
idb.iid(86681).barmor=4293;
idb.iid(86681).socket='MB';
idb.iid(86681).sbstat='str';
idb.iid(86681).sbval=180;
idb.iid(86681).atype=1;
idb.iid(86681).isreforged=0;
idb.iid(86681).istierR=[1];

idb.iid(86813).name='Vizier\''s Ruby Signet (Raid Finder)';
idb.iid(86813).ilvl=483;
idb.iid(86813).str=459;
idb.iid(86813).sta=906;
idb.iid(86813).exp=306;
idb.iid(86813).parry=604;
idb.iid(86813).isreforged=0;

idb.iid(86823).name='Windblade Talons (Raid Finder)';
idb.iid(86823).ilvl=483;
idb.iid(86823).str=725;
idb.iid(86823).sta=1208;
idb.iid(86823).dodge=497;
idb.iid(86823).parry=497;
idb.iid(86823).barmor=3302;
idb.iid(86823).socket='B';
idb.iid(86823).sbstat='parry';
idb.iid(86823).sbval=60;
idb.iid(86823).atype=1;
idb.iid(86823).isreforged=0;

idb.iid(86830).name='Ring of the Shattered Shell (Raid Finder)';
idb.iid(86830).ilvl=483;
idb.iid(86830).str=604;
idb.iid(86830).sta=906;
idb.iid(86830).mast=353;
idb.iid(86830).dodge=432;
idb.iid(86830).isreforged=0;

idb.iid(86832).name='Garalon\''s Hollow Skull (Raid Finder)';
idb.iid(86832).ilvl=483;
idb.iid(86832).str=844;
idb.iid(86832).sta=1626;
idb.iid(86832).dodge=583;
idb.iid(86832).parry=623;
idb.iid(86832).barmor=4293;
idb.iid(86832).socket='MR';
idb.iid(86832).sbstat='sta';
idb.iid(86832).sbval=270;
idb.iid(86832).atype=1;
idb.iid(86832).isreforged=0;

idb.iid(86848).name='Serrated Wasp Bracers (Raid Finder)';
idb.iid(86848).ilvl=483;
idb.iid(86848).str=459;
idb.iid(86848).sta=906;
idb.iid(86848).exp=306;
idb.iid(86848).dodge=604;
idb.iid(86848).barmor=2312;
idb.iid(86848).atype=1;
idb.iid(86848).isreforged=0;

idb.iid(86853).name='Cloak of Raining Blades (Raid Finder)';
idb.iid(86853).ilvl=483;
idb.iid(86853).str=604;
idb.iid(86853).sta=906;
idb.iid(86853).mast=306;
idb.iid(86853).dodge=459;
idb.iid(86853).barmor=1092;
idb.iid(86853).isreforged=0;

idb.iid(86854).name='Articulated Legplates (Raid Finder)';
idb.iid(86854).ilvl=483;
idb.iid(86854).str=664;
idb.iid(86854).sta=1626;
idb.iid(86854).hit=469;
idb.iid(86854).parry=1004;
idb.iid(86854).barmor=4623;
idb.iid(86854).socket='RB';
idb.iid(86854).sbstat='str';
idb.iid(86854).sbval=120;
idb.iid(86854).atype=1;
idb.iid(86854).isreforged=0;

idb.iid(86868).name='Bracers of Defiled Earth (Raid Finder)';
idb.iid(86868).ilvl=483;
idb.iid(86868).str=604;
idb.iid(86868).sta=906;
idb.iid(86868).hit=306;
idb.iid(86868).mast=459;
idb.iid(86868).barmor=2312;
idb.iid(86868).atype=1;
idb.iid(86868).isreforged=0;

idb.iid(86870).name='Deepwater Greatboots (Raid Finder)';
idb.iid(86870).ilvl=483;
idb.iid(86870).str=532;
idb.iid(86870).sta=1208;
idb.iid(86870).hit=376;
idb.iid(86870).parry=757;
idb.iid(86870).barmor=3633;
idb.iid(86870).socket='Y';
idb.iid(86870).sbstat='parry';
idb.iid(86870).sbval=60;
idb.iid(86870).atype=1;
idb.iid(86870).isreforged=0;

idb.iid(86871).name='Shackle of Eversparks (Raid Finder)';
idb.iid(86871).ilvl=483;
idb.iid(86871).str=604;
idb.iid(86871).sta=906;
idb.iid(86871).hit=437;
idb.iid(86871).exp=343;
idb.iid(86871).isreforged=0;

idb.iid(86872).name='Kaolan\''s Withering Necklace (Raid Finder)';
idb.iid(86872).ilvl=483;
idb.iid(86872).str=604;
idb.iid(86872).sta=906;
idb.iid(86872).dodge=402;
idb.iid(86872).parry=402;
idb.iid(86872).isreforged=0;

idb.iid(86881).name='Stuff of Nightmares (Raid Finder)';
idb.iid(86881).ilvl=483;
idb.iid(86881).mast=1021;
idb.iid(86881).isreforged=0;

idb.iid(86883).name='Daybreak Drape (Raid Finder)';
idb.iid(86883).ilvl=483;
idb.iid(86883).str=604;
idb.iid(86883).sta=906;
idb.iid(86883).dodge=392;
idb.iid(86883).parry=409;
idb.iid(86883).barmor=1092;
idb.iid(86883).isreforged=0;

idb.iid(86891).name='Cuirass of the Animated Protector (Raid Finder)';
idb.iid(86891).ilvl=483;
idb.iid(86891).str=924;
idb.iid(86891).sta=1626;
idb.iid(86891).mast=624;
idb.iid(86891).dodge=654;
idb.iid(86891).barmor=5284;
idb.iid(86891).socket='RY';
idb.iid(86891).sbstat='str';
idb.iid(86891).sbval=120;
idb.iid(86891).atype=1;
idb.iid(86891).isreforged=0;

idb.iid(86894).name='Darkmist Vortex (Raid Finder)';
idb.iid(86894).ilvl=483;
idb.iid(86894).str=1021;
idb.iid(86894).isreforged=0;

idb.iid(86903).name='Protector\''s Girdle of Endless Spring (Raid Finder)';
idb.iid(86903).ilvl=483;
idb.iid(86903).str=532;
idb.iid(86903).sta=1208;
idb.iid(86903).exp=368;
idb.iid(86903).dodge=765;
idb.iid(86903).barmor=2972;
idb.iid(86903).socket='B';
idb.iid(86903).sbstat='dodge';
idb.iid(86903).sbval=60;
idb.iid(86903).atype=1;
idb.iid(86903).isreforged=0;

idb.iid(86863).name='Scimitar of Seven Stars (Raid Finder)';
idb.iid(86863).wtype='swo';
idb.iid(86863).ilvl=483;
idb.iid(86863).tooldps=2935.8;
idb.iid(86863).swing=2.6;
idb.iid(86863).avgdmg=7633.5;
idb.iid(86863).str=384;
idb.iid(86863).sta=697;
idb.iid(86863).hit=274;
idb.iid(86863).mast=262;
idb.iid(86863).socket='B';
idb.iid(86863).sbstat='mast';
idb.iid(86863).sbval=60;
idb.iid(86863).isreforged=0;

idb.iid(86906).name='Kilrak, Jaws of Terror (Raid Finder)';
idb.iid(86906).wtype='swo';
idb.iid(86906).ilvl=483;
idb.iid(86906).tooldps=2935.8;
idb.iid(86906).swing=2.6;
idb.iid(86906).avgdmg=7633.5;
idb.iid(86906).str=384;
idb.iid(86906).sta=697;
idb.iid(86906).hit=274;
idb.iid(86906).mast=262;
idb.iid(86906).socket='B';
idb.iid(86906).sbstat='hit';
idb.iid(86906).sbval=60;
idb.iid(86906).isreforged=0;

idb.iid(85922).name='Beads of the Mogu\''shi';
idb.iid(85922).ilvl=489;
idb.iid(85922).str=485;
idb.iid(85922).sta=958;
idb.iid(85922).exp=323;
idb.iid(85922).dodge=638;
idb.iid(85922).isreforged=0;

idb.iid(85983).name='Bracers of Six Oxen';
idb.iid(85983).ilvl=489;
idb.iid(85983).str=638;
idb.iid(85983).sta=958;
idb.iid(85983).dodge=426;
idb.iid(85983).parry=426;
idb.iid(85983).barmor=2359;
idb.iid(85983).atype=1;
idb.iid(85983).isreforged=0;

idb.iid(85992).name='Sollerets of Spirit Splitting';
idb.iid(85992).ilvl=489;
idb.iid(85992).str=771;
idb.iid(85992).sta=1277;
idb.iid(85992).mast=536;
idb.iid(85992).dodge=507;
idb.iid(85992).barmor=3707;
idb.iid(85992).socket='Y';
idb.iid(85992).sbstat='dodge';
idb.iid(85992).sbval=60;
idb.iid(85992).atype=1;
idb.iid(85992).isreforged=0;

idb.iid(86042).name='Jade Charioteer Figurine';
idb.iid(86042).ilvl=489;
idb.iid(86042).str=1079;
idb.iid(86042).isreforged=0;

idb.iid(86046).name='Jade Warlord Figurine';
idb.iid(86046).ilvl=489;
idb.iid(86046).sta=1619;
idb.iid(86046).isreforged=0;

idb.iid(86075).name='Steelskin, Qiang\''s Impervious Shield';
idb.iid(86075).ilvl=489;
idb.iid(86075).str=638;
idb.iid(86075).sta=958;
idb.iid(86075).dodge=415;
idb.iid(86075).parry=432;
idb.iid(86075).barmor=17293;
idb.iid(86075).isreforged=0;

idb.iid(86080).name='Shoulderguards of the Unflanked';
idb.iid(86080).ilvl=489;
idb.iid(86080).str=567;
idb.iid(86080).sta=1277;
idb.iid(86080).hit=391;
idb.iid(86080).parry=811;
idb.iid(86080).barmor=4043;
idb.iid(86080).socket='R';
idb.iid(86080).sbstat='sta';
idb.iid(86080).sbval=90;
idb.iid(86080).atype=1;
idb.iid(86080).isreforged=0;

idb.iid(86131).name='Vial of Dragon\''s Blood';
idb.iid(86131).ilvl=489;
idb.iid(86131).mast=1079;
idb.iid(86131).isreforged=0;

idb.iid(86132).name='Bottle of Infinite Stars';
idb.iid(86132).ilvl=489;
idb.iid(86132).mast=1079;
idb.iid(86132).isreforged=0;

idb.iid(86134).name='Star-Stealer Waistguard';
idb.iid(86134).ilvl=489;
idb.iid(86134).str=691;
idb.iid(86134).sta=1277;
idb.iid(86134).mast=418;
idb.iid(86134).dodge=529;
idb.iid(86134).barmor=3033;
idb.iid(86134).socket='YB';
idb.iid(86134).sbstat='dodge';
idb.iid(86134).sbval=120;
idb.iid(86134).atype=1;
idb.iid(86134).isreforged=0;

idb.iid(86147).name='Qin-xi\''s Polarizing Seal';
idb.iid(86147).ilvl=489;
idb.iid(86147).spi=1079;
idb.iid(86147).isreforged=0;

idb.iid(88746).name='Gloves of the Overwhelming Swarm';
idb.iid(88746).ilvl=489;
idb.iid(88746).str=851;
idb.iid(88746).sta=1277;
idb.iid(88746).mast=498;
idb.iid(88746).parry=609;
idb.iid(88746).barmor=3370;
idb.iid(88746).atype=1;
idb.iid(88746).isreforged=0;

idb.iid(88864).name='Yu\''lon Guardian Boots';
idb.iid(88864).ilvl=489;
idb.iid(88864).str=851;
idb.iid(88864).sta=1277;
idb.iid(88864).dodge=431;
idb.iid(88864).parry=647;
idb.iid(88864).barmor=3707;
idb.iid(88864).atype=1;
idb.iid(88864).isreforged=0;

idb.iid(88880).name='Battle Shadow Bracers';
idb.iid(88880).ilvl=489;
idb.iid(88880).str=485;
idb.iid(88880).sta=958;
idb.iid(88880).hit=323;
idb.iid(88880).parry=638;
idb.iid(88880).barmor=2359;
idb.iid(88880).atype=1;
idb.iid(88880).isreforged=0;

idb.iid(89056).name='Klaxxi Lash of the Consumer';
idb.iid(89056).ilvl=489;
idb.iid(89056).str=529;
idb.iid(89056).sta=1277;
idb.iid(89056).hit=458;
idb.iid(89056).parry=811;
idb.iid(89056).barmor=3033;
idb.iid(89056).socket='B';
idb.iid(89056).sbstat='parry';
idb.iid(89056).sbval=60;
idb.iid(89056).atype=1;
idb.iid(89056).isreforged=0;

idb.iid(89066).name='Paragon\''s Pale Pendant';
idb.iid(89066).ilvl=489;
idb.iid(89066).str=485;
idb.iid(89066).sta=958;
idb.iid(89066).hit=323;
idb.iid(89066).parry=638;
idb.iid(89066).isreforged=0;

idb.iid(89071).name='Alani\''s Inflexible Ring';
idb.iid(89071).ilvl=489;
idb.iid(89071).str=638;
idb.iid(89071).sta=958;
idb.iid(89071).dodge=468;
idb.iid(89071).parry=353;
idb.iid(89071).isreforged=0;

idb.iid(89075).name='Yi\''s Cloak of Courage';
idb.iid(89075).ilvl=489;
idb.iid(89075).str=638;
idb.iid(89075).sta=958;
idb.iid(89075).mast=373;
idb.iid(89075).parry=457;
idb.iid(89075).barmor=1115;
idb.iid(89075).isreforged=0;

idb.iid(89079).name='Lao-Chin\''s Liquid Courage';
idb.iid(89079).ilvl=489;
idb.iid(89079).sta=1619;
idb.iid(89079).isreforged=0;

idb.iid(89083).name='Iron Belly Wok';
idb.iid(89083).ilvl=489;
idb.iid(89083).str=1079;
idb.iid(89083).isreforged=0;

idb.iid(89093).name='Kovok\''s Riven Legguards';
idb.iid(89093).ilvl=489;
idb.iid(89093).str=791;
idb.iid(89093).sta=1719;
idb.iid(89093).exp=540;
idb.iid(89093).dodge=1106;
idb.iid(89093).barmor=4717;
idb.iid(89093).socket='R';
idb.iid(89093).sbstat='str';
idb.iid(89093).sbval=60;
idb.iid(89093).atype=1;
idb.iid(89093).isreforged=0;

idb.iid(89216).name='Yi\''s Least Favorite Helmet';
idb.iid(89216).ilvl=489;
idb.iid(89216).str=906;
idb.iid(89216).sta=1719;
idb.iid(89216).mast=570;
idb.iid(89216).dodge=680;
idb.iid(89216).barmor=4380;
idb.iid(89216).socket='MB';
idb.iid(89216).sbstat='sta';
idb.iid(89216).sbval=270;
idb.iid(89216).atype=1;
idb.iid(89216).isreforged=0;

idb.iid(89346).name='Shoulders of Autumnlight';
idb.iid(89346).ilvl=489;
idb.iid(89346).str=529;
idb.iid(89346).sta=1277;
idb.iid(89346).exp=458;
idb.iid(89346).dodge=811;
idb.iid(89346).barmor=4043;
idb.iid(89346).socket='Y';
idb.iid(89346).sbstat='sta';
idb.iid(89346).sbval=90;
idb.iid(89346).atype=1;
idb.iid(89346).isreforged=0;

idb.iid(86130).name='Elegion, the Fanged Crescent';
idb.iid(86130).wtype='axe';
idb.iid(86130).ilvl=489;
idb.iid(86130).tooldps=3104.6;
idb.iid(86130).swing=2.6;
idb.iid(86130).avgdmg=8072;
idb.iid(86130).str=491;
idb.iid(86130).sta=737;
idb.iid(86130).hit=342;
idb.iid(86130).exp=303;
idb.iid(86130).isreforged=0;

idb.iid(85319).name='White Tiger Shoulderguards';
idb.iid(85319).ilvl=496;
idb.iid(85319).str=829;
idb.iid(85319).sta=1363;
idb.iid(85319).exp=460;
idb.iid(85319).mast=611;
idb.iid(85319).barmor=4137;
idb.iid(85319).socket='B';
idb.iid(85319).sbstat='sta';
idb.iid(85319).sbval=90;
idb.iid(85319).atype=1;
idb.iid(85319).isreforged=0;
idb.iid(85319).istierP=[1];

idb.iid(85320).name='White Tiger Legguards';
idb.iid(85320).ilvl=496;
idb.iid(85320).str=1143;
idb.iid(85320).sta=1835;
idb.iid(85320).mast=812;
idb.iid(85320).dodge=715;
idb.iid(85320).barmor=4827;
idb.iid(85320).socket='R';
idb.iid(85320).sbstat='sta';
idb.iid(85320).sbval=90;
idb.iid(85320).atype=1;
idb.iid(85320).isreforged=0;
idb.iid(85320).istierP=[1];

idb.iid(85321).name='White Tiger Faceguard';
idb.iid(85321).ilvl=496;
idb.iid(85321).str=690;
idb.iid(85321).sta=1835;
idb.iid(85321).exp=460;
idb.iid(85321).parry=1143;
idb.iid(85321).barmor=4482;
idb.iid(85321).socket='MB';
idb.iid(85321).sbstat='sta';
idb.iid(85321).sbval=270;
idb.iid(85321).atype=1;
idb.iid(85321).isreforged=0;
idb.iid(85321).istierP=[1];

idb.iid(85322).name='White Tiger Handguards';
idb.iid(85322).ilvl=496;
idb.iid(85322).str=691;
idb.iid(85322).sta=1363;
idb.iid(85322).hit=460;
idb.iid(85322).dodge=909;
idb.iid(85322).barmor=3448;
idb.iid(85322).atype=1;
idb.iid(85322).isreforged=0;
idb.iid(85322).istierP=[1];

idb.iid(85323).name='White Tiger Chestguard';
idb.iid(85323).ilvl=496;
idb.iid(85323).str=1063;
idb.iid(85323).sta=1835;
idb.iid(85323).hit=538;
idb.iid(85323).parry=868;
idb.iid(85323).barmor=5517;
idb.iid(85323).socket='YY';
idb.iid(85323).sbstat='parry';
idb.iid(85323).sbval=120;
idb.iid(85323).atype=1;
idb.iid(85323).isreforged=0;
idb.iid(85323).istierP=[1];

idb.iid(85340).name='White Tiger Legplates';
idb.iid(85340).ilvl=496;
idb.iid(85340).str=1143;
idb.iid(85340).sta=1835;
idb.iid(85340).exp=675;
idb.iid(85340).mast=835;
idb.iid(85340).barmor=4827;
idb.iid(85340).socket='R';
idb.iid(85340).sbstat='str';
idb.iid(85340).sbval=60;
idb.iid(85340).atype=1;
idb.iid(85340).isreforged=0;
idb.iid(85340).istierR=[1];

idb.iid(85341).name='White Tiger Helmet';
idb.iid(85341).ilvl=496;
idb.iid(85341).str=983;
idb.iid(85341).sta=1835;
idb.iid(85341).hit=735;
idb.iid(85341).mast=655;
idb.iid(85341).barmor=4482;
idb.iid(85341).socket='MB';
idb.iid(85341).sbstat='str';
idb.iid(85341).sbval=180;
idb.iid(85341).atype=1;
idb.iid(85341).isreforged=0;
idb.iid(85341).istierR=[1];

idb.iid(86155).name='Vizier\''s Ruby Signet';
idb.iid(86155).ilvl=496;
idb.iid(86155).str=518;
idb.iid(86155).sta=1022;
idb.iid(86155).exp=345;
idb.iid(86155).parry=682;
idb.iid(86155).isreforged=0;

idb.iid(86165).name='Windblade Talons';
idb.iid(86165).ilvl=496;
idb.iid(86165).str=829;
idb.iid(86165).sta=1363;
idb.iid(86165).dodge=566;
idb.iid(86165).parry=566;
idb.iid(86165).barmor=3448;
idb.iid(86165).socket='B';
idb.iid(86165).sbstat='parry';
idb.iid(86165).sbval=60;
idb.iid(86165).atype=1;
idb.iid(86165).isreforged=0;

idb.iid(86172).name='Ring of the Shattered Shell';
idb.iid(86172).ilvl=496;
idb.iid(86172).str=682;
idb.iid(86172).sta=1022;
idb.iid(86172).mast=399;
idb.iid(86172).dodge=487;
idb.iid(86172).isreforged=0;

idb.iid(86174).name='Garalon\''s Hollow Skull';
idb.iid(86174).ilvl=496;
idb.iid(86174).str=983;
idb.iid(86174).sta=1835;
idb.iid(86174).dodge=675;
idb.iid(86174).parry=715;
idb.iid(86174).barmor=4482;
idb.iid(86174).socket='MR';
idb.iid(86174).sbstat='sta';
idb.iid(86174).sbval=270;
idb.iid(86174).atype=1;
idb.iid(86174).isreforged=0;

idb.iid(86190).name='Serrated Wasp Bracers';
idb.iid(86190).ilvl=496;
idb.iid(86190).str=518;
idb.iid(86190).sta=1022;
idb.iid(86190).exp=345;
idb.iid(86190).dodge=682;
idb.iid(86190).barmor=2414;
idb.iid(86190).atype=1;
idb.iid(86190).isreforged=0;

idb.iid(86202).name='Cloak of Raining Blades';
idb.iid(86202).ilvl=496;
idb.iid(86202).str=682;
idb.iid(86202).sta=1022;
idb.iid(86202).mast=345;
idb.iid(86202).dodge=518;
idb.iid(86202).barmor=1140;
idb.iid(86202).isreforged=0;

idb.iid(86203).name='Articulated Legplates';
idb.iid(86203).ilvl=496;
idb.iid(86203).str=770;
idb.iid(86203).sta=1835;
idb.iid(86203).hit=540;
idb.iid(86203).parry=1143;
idb.iid(86203).barmor=4827;
idb.iid(86203).socket='RB';
idb.iid(86203).sbstat='str';
idb.iid(86203).sbval=120;
idb.iid(86203).atype=1;
idb.iid(86203).isreforged=0;

idb.iid(86230).name='Bracers of Defiled Earth';
idb.iid(86230).ilvl=496;
idb.iid(86230).str=682;
idb.iid(86230).sta=1022;
idb.iid(86230).hit=345;
idb.iid(86230).mast=518;
idb.iid(86230).barmor=2414;
idb.iid(86230).atype=1;
idb.iid(86230).isreforged=0;

idb.iid(86232).name='Deepwater Greatboots';
idb.iid(86232).ilvl=496;
idb.iid(86232).str=611;
idb.iid(86232).sta=1363;
idb.iid(86232).hit=428;
idb.iid(86232).parry=861;
idb.iid(86232).barmor=3793;
idb.iid(86232).socket='Y';
idb.iid(86232).sbstat='parry';
idb.iid(86232).sbval=60;
idb.iid(86232).atype=1;
idb.iid(86232).isreforged=0;

idb.iid(86233).name='Shackle of Eversparks';
idb.iid(86233).ilvl=496;
idb.iid(86233).str=682;
idb.iid(86233).sta=1022;
idb.iid(86233).hit=494;
idb.iid(86233).exp=388;
idb.iid(86233).isreforged=0;

idb.iid(86234).name='Kaolan\''s Withering Necklace';
idb.iid(86234).ilvl=496;
idb.iid(86234).str=682;
idb.iid(86234).sta=1022;
idb.iid(86234).dodge=454;
idb.iid(86234).parry=454;
idb.iid(86234).isreforged=0;

idb.iid(86323).name='Stuff of Nightmares';
idb.iid(86323).ilvl=496;
idb.iid(86323).mast=1152;
idb.iid(86323).isreforged=0;

idb.iid(86325).name='Daybreak Drape';
idb.iid(86325).ilvl=496;
idb.iid(86325).str=682;
idb.iid(86325).sta=1022;
idb.iid(86325).dodge=443;
idb.iid(86325).parry=461;
idb.iid(86325).barmor=1140;
idb.iid(86325).isreforged=0;

idb.iid(86333).name='Cuirass of the Animated Protector';
idb.iid(86333).ilvl=496;
idb.iid(86333).str=1063;
idb.iid(86333).sta=1835;
idb.iid(86333).mast=715;
idb.iid(86333).dodge=748;
idb.iid(86333).barmor=5517;
idb.iid(86333).socket='RY';
idb.iid(86333).sbstat='str';
idb.iid(86333).sbval=120;
idb.iid(86333).atype=1;
idb.iid(86333).isreforged=0;

idb.iid(86336).name='Darkmist Vortex';
idb.iid(86336).ilvl=496;
idb.iid(86336).str=1152;
idb.iid(86336).isreforged=0;

idb.iid(86384).name='Protector\''s Girdle of Endless Spring';
idb.iid(86384).ilvl=496;
idb.iid(86384).str=611;
idb.iid(86384).sta=1363;
idb.iid(86384).exp=420;
idb.iid(86384).dodge=869;
idb.iid(86384).barmor=3103;
idb.iid(86384).socket='B';
idb.iid(86384).sbstat='dodge';
idb.iid(86384).sbval=60;
idb.iid(86384).atype=1;
idb.iid(86384).isreforged=0;

idb.iid(86219).name='Scimitar of Seven Stars';
idb.iid(86219).wtype='swo';
idb.iid(86219).ilvl=496;
idb.iid(86219).tooldps=3313.9;
idb.iid(86219).swing=2.6;
idb.iid(86219).avgdmg=8616;
idb.iid(86219).str=444;
idb.iid(86219).sta=786;
idb.iid(86219).hit=315;
idb.iid(86219).mast=301;
idb.iid(86219).socket='B';
idb.iid(86219).sbstat='mast';
idb.iid(86219).sbval=60;
idb.iid(86219).isreforged=0;

idb.iid(86387).name='Kilrak, Jaws of Terror';
idb.iid(86387).wtype='swo';
idb.iid(86387).ilvl=496;
idb.iid(86387).tooldps=3313.9;
idb.iid(86387).swing=2.6;
idb.iid(86387).avgdmg=8616;
idb.iid(86387).str=444;
idb.iid(86387).sta=786;
idb.iid(86387).hit=315;
idb.iid(86387).mast=301;
idb.iid(86387).socket='B';
idb.iid(86387).sbstat='hit';
idb.iid(86387).sbval=60;
idb.iid(86387).isreforged=0;

idb.iid(87016).name='Beads of the Mogu\''shi (Heroic)';
idb.iid(87016).ilvl=502;
idb.iid(87016).str=548;
idb.iid(87016).sta=1081;
idb.iid(87016).exp=365;
idb.iid(87016).dodge=720;
idb.iid(87016).isreforged=0;

idb.iid(87025).name='Bracers of Six Oxen (Heroic)';
idb.iid(87025).ilvl=502;
idb.iid(87025).str=720;
idb.iid(87025).sta=1081;
idb.iid(87025).dodge=480;
idb.iid(87025).parry=480;
idb.iid(87025).barmor=2461;
idb.iid(87025).atype=1;
idb.iid(87025).isreforged=0;

idb.iid(87035).name='Sollerets of Spirit Splitting (Heroic)';
idb.iid(87035).ilvl=502;
idb.iid(87035).str=881;
idb.iid(87035).sta=1441;
idb.iid(87035).mast=612;
idb.iid(87035).dodge=577;
idb.iid(87035).barmor=3867;
idb.iid(87035).socket='Y';
idb.iid(87035).sbstat='dodge';
idb.iid(87035).sbval=60;
idb.iid(87035).atype=1;
idb.iid(87035).isreforged=0;

idb.iid(87049).name='Shoulderguards of the Unflanked (Heroic)';
idb.iid(87049).ilvl=502;
idb.iid(87049).str=650;
idb.iid(87049).sta=1441;
idb.iid(87049).hit=447;
idb.iid(87049).parry=921;
idb.iid(87049).barmor=4218;
idb.iid(87049).socket='R';
idb.iid(87049).sbstat='sta';
idb.iid(87049).sbval=90;
idb.iid(87049).atype=1;
idb.iid(87049).isreforged=0;

idb.iid(87050).name='Steelskin, Qiang\''s Impervious Shield (Heroic)';
idb.iid(87050).ilvl=502;
idb.iid(87050).str=720;
idb.iid(87050).sta=1081;
idb.iid(87050).dodge=468;
idb.iid(87050).parry=488;
idb.iid(87050).barmor=18040;
idb.iid(87050).isreforged=0;

idb.iid(87057).name='Bottle of Infinite Stars (Heroic)';
idb.iid(87057).ilvl=502;
idb.iid(87057).mast=1218;
idb.iid(87057).isreforged=0;

idb.iid(87060).name='Star-Stealer Waistguard (Heroic)';
idb.iid(87060).ilvl=502;
idb.iid(87060).str=801;
idb.iid(87060).sta=1441;
idb.iid(87060).mast=482;
idb.iid(87060).dodge=607;
idb.iid(87060).barmor=3164;
idb.iid(87060).socket='YB';
idb.iid(87060).sbstat='dodge';
idb.iid(87060).sbval=120;
idb.iid(87060).atype=1;
idb.iid(87060).isreforged=0;

idb.iid(87063).name='Vial of Dragon\''s Blood (Heroic)';
idb.iid(87063).ilvl=502;
idb.iid(87063).mast=1218;
idb.iid(87063).isreforged=0;

idb.iid(87075).name='Qin-xi\''s Polarizing Seal (Heroic)';
idb.iid(87075).ilvl=502;
idb.iid(87075).spi=1218;
idb.iid(87075).isreforged=0;

idb.iid(87082).name='Jade Charioteer Figurine (Heroic)';
idb.iid(87082).ilvl=502;
idb.iid(87082).str=1218;
idb.iid(87082).isreforged=0;

idb.iid(87083).name='Jade Warlord Figurine (Heroic)';
idb.iid(87083).ilvl=502;
idb.iid(87083).sta=1827;
idb.iid(87083).isreforged=0;

idb.iid(87062).name='Elegion, the Fanged Crescent (Heroic)';
idb.iid(87062).wtype='axe';
idb.iid(87062).ilvl=502;
idb.iid(87062).tooldps=3504.4;
idb.iid(87062).swing=2.6;
idb.iid(87062).avgdmg=9111.5;
idb.iid(87062).str=554;
idb.iid(87062).sta=832;
idb.iid(87062).hit=386;
idb.iid(87062).exp=342;
idb.iid(87062).isreforged=0;

idb.iid(86944).name='Articulated Legplates (Heroic)';
idb.iid(86944).ilvl=509;
idb.iid(86944).str=889;
idb.iid(86944).sta=2071;
idb.iid(86944).hit=619;
idb.iid(86944).parry=1300;
idb.iid(86944).barmor=5031;
idb.iid(86944).socket='RB';
idb.iid(86944).sbstat='str';
idb.iid(86944).sbval=120;
idb.iid(86944).atype=1;
idb.iid(86944).isreforged=0;

idb.iid(86946).name='Vizier\''s Ruby Signet (Heroic)';
idb.iid(86946).ilvl=509;
idb.iid(86946).str=585;
idb.iid(86946).sta=1154;
idb.iid(86946).exp=390;
idb.iid(86946).parry=769;
idb.iid(86946).isreforged=0;

idb.iid(86956).name='Windblade Talons (Heroic)';
idb.iid(86956).ilvl=509;
idb.iid(86956).str=946;
idb.iid(86956).sta=1538;
idb.iid(86956).dodge=644;
idb.iid(86956).parry=644;
idb.iid(86956).barmor=3593;
idb.iid(86956).socket='B';
idb.iid(86956).sbstat='parry';
idb.iid(86956).sbval=60;
idb.iid(86956).atype=1;
idb.iid(86956).isreforged=0;

idb.iid(86966).name='Garalon\''s Hollow Skull (Heroic)';
idb.iid(86966).ilvl=509;
idb.iid(86966).str=1140;
idb.iid(86966).sta=2071;
idb.iid(86966).dodge=780;
idb.iid(86966).parry=820;
idb.iid(86966).barmor=4671;
idb.iid(86966).socket='MR';
idb.iid(86966).sbstat='sta';
idb.iid(86966).sbval=270;
idb.iid(86966).atype=1;
idb.iid(86966).isreforged=0;

idb.iid(86968).name='Ring of the Shattered Shell (Heroic)';
idb.iid(86968).ilvl=509;
idb.iid(86968).str=769;
idb.iid(86968).sta=1154;
idb.iid(86968).mast=450;
idb.iid(86968).dodge=550;
idb.iid(86968).isreforged=0;

idb.iid(86980).name='Cloak of Raining Blades (Heroic)';
idb.iid(86980).ilvl=509;
idb.iid(86980).str=769;
idb.iid(86980).sta=1154;
idb.iid(86980).mast=390;
idb.iid(86980).dodge=585;
idb.iid(86980).barmor=1189;
idb.iid(86980).isreforged=0;

idb.iid(87001).name='Serrated Wasp Bracers (Heroic)';
idb.iid(87001).ilvl=509;
idb.iid(87001).str=585;
idb.iid(87001).sta=1154;
idb.iid(87001).exp=390;
idb.iid(87001).dodge=769;
idb.iid(87001).barmor=2515;
idb.iid(87001).atype=1;
idb.iid(87001).isreforged=0;

idb.iid(87101).name='White Tiger Helmet (Heroic)';
idb.iid(87101).ilvl=509;
idb.iid(87101).str=1140;
idb.iid(87101).sta=2071;
idb.iid(87101).hit=840;
idb.iid(87101).mast=760;
idb.iid(87101).barmor=4671;
idb.iid(87101).socket='MB';
idb.iid(87101).sbstat='str';
idb.iid(87101).sbval=180;
idb.iid(87101).atype=1;
idb.iid(87101).isreforged=0;
idb.iid(87101).istierR=[1];

idb.iid(87102).name='White Tiger Legplates (Heroic)';
idb.iid(87102).ilvl=509;
idb.iid(87102).str=1300;
idb.iid(87102).sta=2071;
idb.iid(87102).exp=767;
idb.iid(87102).mast=947;
idb.iid(87102).barmor=5031;
idb.iid(87102).socket='R';
idb.iid(87102).sbstat='str';
idb.iid(87102).sbval=60;
idb.iid(87102).atype=1;
idb.iid(87102).isreforged=0;
idb.iid(87102).istierR=[1];

idb.iid(87109).name='White Tiger Chestguard (Heroic)';
idb.iid(87109).ilvl=509;
idb.iid(87109).str=1220;
idb.iid(87109).sta=2071;
idb.iid(87109).hit=622;
idb.iid(87109).parry=985;
idb.iid(87109).barmor=5749;
idb.iid(87109).socket='YY';
idb.iid(87109).sbstat='parry';
idb.iid(87109).sbval=120;
idb.iid(87109).atype=1;
idb.iid(87109).isreforged=0;
idb.iid(87109).istierP=[1];

idb.iid(87110).name='White Tiger Handguards (Heroic)';
idb.iid(87110).ilvl=509;
idb.iid(87110).str=779;
idb.iid(87110).sta=1538;
idb.iid(87110).hit=519;
idb.iid(87110).dodge=1026;
idb.iid(87110).barmor=3593;
idb.iid(87110).atype=1;
idb.iid(87110).isreforged=0;
idb.iid(87110).istierP=[1];

idb.iid(87111).name='White Tiger Faceguard (Heroic)';
idb.iid(87111).ilvl=509;
idb.iid(87111).str=809;
idb.iid(87111).sta=2071;
idb.iid(87111).exp=539;
idb.iid(87111).parry=1300;
idb.iid(87111).barmor=4671;
idb.iid(87111).socket='MB';
idb.iid(87111).sbstat='sta';
idb.iid(87111).sbval=270;
idb.iid(87111).atype=1;
idb.iid(87111).isreforged=0;
idb.iid(87111).istierP=[1];

idb.iid(87112).name='White Tiger Legguards (Heroic)';
idb.iid(87112).ilvl=509;
idb.iid(87112).str=1300;
idb.iid(87112).sta=2071;
idb.iid(87112).mast=921;
idb.iid(87112).dodge=812;
idb.iid(87112).barmor=5031;
idb.iid(87112).socket='R';
idb.iid(87112).sbstat='sta';
idb.iid(87112).sbval=90;
idb.iid(87112).atype=1;
idb.iid(87112).isreforged=0;
idb.iid(87112).istierP=[1];

idb.iid(87113).name='White Tiger Shoulderguards (Heroic)';
idb.iid(87113).ilvl=509;
idb.iid(87113).str=946;
idb.iid(87113).sta=1538;
idb.iid(87113).exp=519;
idb.iid(87113).mast=699;
idb.iid(87113).barmor=4312;
idb.iid(87113).socket='B';
idb.iid(87113).sbstat='sta';
idb.iid(87113).sbval=90;
idb.iid(87113).atype=1;
idb.iid(87113).isreforged=0;
idb.iid(87113).istierP=[1];

idb.iid(87145).name='Bracers of Defiled Earth (Heroic)';
idb.iid(87145).ilvl=509;
idb.iid(87145).str=769;
idb.iid(87145).sta=1154;
idb.iid(87145).hit=390;
idb.iid(87145).mast=585;
idb.iid(87145).barmor=2515;
idb.iid(87145).atype=1;
idb.iid(87145).isreforged=0;

idb.iid(87146).name='Deepwater Greatboots (Heroic)';
idb.iid(87146).ilvl=509;
idb.iid(87146).str=699;
idb.iid(87146).sta=1538;
idb.iid(87146).hit=487;
idb.iid(87146).parry=978;
idb.iid(87146).barmor=3953;
idb.iid(87146).socket='Y';
idb.iid(87146).sbstat='parry';
idb.iid(87146).sbval=60;
idb.iid(87146).atype=1;
idb.iid(87146).isreforged=0;

idb.iid(87147).name='Shackle of Eversparks (Heroic)';
idb.iid(87147).ilvl=509;
idb.iid(87147).str=769;
idb.iid(87147).sta=1154;
idb.iid(87147).hit=557;
idb.iid(87147).exp=438;
idb.iid(87147).isreforged=0;

idb.iid(87148).name='Kaolan\''s Withering Necklace (Heroic)';
idb.iid(87148).ilvl=509;
idb.iid(87148).str=769;
idb.iid(87148).sta=1154;
idb.iid(87148).dodge=513;
idb.iid(87148).parry=513;
idb.iid(87148).isreforged=0;

idb.iid(87159).name='Daybreak Drape (Heroic)';
idb.iid(87159).ilvl=509;
idb.iid(87159).str=769;
idb.iid(87159).sta=1154;
idb.iid(87159).dodge=500;
idb.iid(87159).parry=521;
idb.iid(87159).barmor=1189;
idb.iid(87159).isreforged=0;

idb.iid(87160).name='Stuff of Nightmares (Heroic)';
idb.iid(87160).ilvl=509;
idb.iid(87160).mast=1300;
idb.iid(87160).isreforged=0;

idb.iid(87171).name='Cuirass of the Animated Protector (Heroic)';
idb.iid(87171).ilvl=509;
idb.iid(87171).str=1220;
idb.iid(87171).sta=2071;
idb.iid(87171).mast=817;
idb.iid(87171).dodge=854;
idb.iid(87171).barmor=5749;
idb.iid(87171).socket='RY';
idb.iid(87171).sbstat='str';
idb.iid(87171).sbval=120;
idb.iid(87171).atype=1;
idb.iid(87171).isreforged=0;

idb.iid(87172).name='Darkmist Vortex (Heroic)';
idb.iid(87172).ilvl=509;
idb.iid(87172).str=1300;
idb.iid(87172).isreforged=0;

idb.iid(87185).name='Protector\''s Girdle of Endless Spring (Heroic)';
idb.iid(87185).ilvl=509;
idb.iid(87185).str=699;
idb.iid(87185).sta=1538;
idb.iid(87185).exp=479;
idb.iid(87185).dodge=986;
idb.iid(87185).barmor=3234;
idb.iid(87185).socket='B';
idb.iid(87185).sbstat='dodge';
idb.iid(87185).sbval=60;
idb.iid(87185).atype=1;
idb.iid(87185).isreforged=0;

idb.iid(86987).name='Scimitar of Seven Stars (Heroic)';
idb.iid(86987).wtype='swo';
idb.iid(86987).ilvl=509;
idb.iid(86987).tooldps=3740.6;
idb.iid(86987).swing=2.6;
idb.iid(86987).avgdmg=9725.5;
idb.iid(86987).str=512;
idb.iid(86987).sta=887;
idb.iid(86987).hit=360;
idb.iid(86987).mast=345;
idb.iid(86987).socket='B';
idb.iid(86987).sbstat='mast';
idb.iid(86987).sbval=60;
idb.iid(86987).isreforged=0;

idb.iid(87173).name='Kilrak, Jaws of Terror (Heroic)';
idb.iid(87173).wtype='swo';
idb.iid(87173).ilvl=509;
idb.iid(87173).tooldps=3740.6;
idb.iid(87173).swing=2.6;
idb.iid(87173).avgdmg=9725.5;
idb.iid(87173).str=512;
idb.iid(87173).sta=887;
idb.iid(87173).hit=360;
idb.iid(87173).mast=345;
idb.iid(87173).socket='B';
idb.iid(87173).sbstat='hit';
idb.iid(87173).sbval=60;
idb.iid(87173).isreforged=0;

%% Enchant section  
%Enchants work exactly the same way that items do.  There is an idb
%structure that contains all of the relevant enchants, according to the
%spell_id value. Since it has the same form, we can use the same equip()
%function.
%Note that several entries have the generator's 'name' field, instead
%of the effect's. See the Arcanum entries, for a few examples.

%% generic (multiple slots)
idb.sid(78166).name='Heavy Savage Armor Kit';
idb.sid(78166).sta=44;

%% Head
idb.sid(86931).name='Arcanum of the Earthen Ring';
idb.sid(86931).sta=90;
idb.sid(86931).dodge=35;

idb.sid(86933).name='Arcanum of the Dragonmaw/Wildhammer';
idb.sid(86933).str=60;
idb.sid(86933).mast=35;

%% Shoulder
idb.sid(86847).name='Inscription of Unbreakable Quartz';
idb.sid(86847).sta=45;
idb.sid(86847).dodge=20;

idb.sid(86900).name='Inscription of Jagged Stone';
idb.sid(86900).str=30;
idb.sid(86900).crit=20;

idb.sid(86909).name='Inscription of Shattered Crystal';
idb.sid(86909).agi=30;
idb.sid(86909).mast=20;

idb.sid(86854).name='Greater Inscription of Unbreakable Quartz';
idb.sid(86854).sta=75;
idb.sid(86854).dodge=25;

idb.sid(86901).name='Greater Inscription of Jagged Stone';
idb.sid(86901).str=50;
idb.sid(86901).crit=25;

idb.sid(86907).name='Greater Inscription of Shattered Crystal';
idb.sid(86907).agi=50;
idb.sid(86907).mast=25;

idb.sid(86375).name='Swiftsteel Inscription';
idb.sid(86375).agi=130;
idb.sid(86375).mast=25;

idb.sid(86401).name='Lionsmane Inscription';
idb.sid(86401).str=130;
idb.sid(86401).crit=25;

idb.sid(86402).name='Inscription of the Earth Prince';
idb.sid(86402).sta=195;
idb.sid(86402).dodge=25;

%% Cloak
idb.sid(74234).name='Enchant Cloak - Protection';
idb.sid(74234).earmor=250;

idb.sid(74247).name='Enchant Cloak - Greater Critical Strike';
idb.sid(74247).crit=65;

%% Chest
idb.sid(74251).name='Enchant Chest - Greater Stamina';
idb.sid(74251).sta=75;

idb.sid(74250).name='Enchant Chest - Peerless Stats';
idb.sid(74250).sta=20;
idb.sid(74250).str=20;
idb.sid(74250).agi=20;
idb.sid(74250).int=20;

%% Wrists
idb.sid(62256).name='Enchant Bracer - Major Stamina';
idb.sid(62256).sta=40;

idb.sid(85007).name='Draconic Embossment - Stamina';
idb.sid(85007).sta=195;

idb.sid(85009).name='Draconic Embossment - Strength';
idb.sid(85009).sta=130;

idb.sid(74229).name='Enchant Bracer - Dodge';
idb.sid(74229).dodge=50;

idb.sid(74232).name='Enchant Bracer - Precision';
idb.sid(74232).hit=50;

idb.sid(74239).name='Enchant Bracer - Greater Expertise';
idb.sid(74239).exp=50;

idb.sid(74248).name='Enchant Bracer - Greater Critical Strike';
idb.sid(74248).crit=65;

idb.sid(96261).name='Enchant Bracer - Major Strength';
idb.sid(96261).str=50;

%% Hands
idb.sid(74254).name='Enchant Gloves - Mighty Strength';
idb.sid(74254).str=50;

idb.sid(74255).name='Enchant Gloves - Greater Mastery';
idb.sid(74255).mast=65;

idb.sid(74220).name='Enchant Gloves - Greater Expertise';
idb.sid(74220).exp=50;

idb.sid(82175).name='Synapse Springs';

idb.sid(82177).name='Quickflip Deflection Plates';

%% Waist
idb.sid(76168).name='Ebonsteel Belt Buckle';
idb.sid(76168).socket='P';

%% Legs
idb.sid(78169).name='Scorched Leg Armor';
idb.sid(78169).ap=110;
idb.sid(78169).crit=45;

idb.sid(78170).name='Twilight Leg Armor';
idb.sid(78170).sta=85;
idb.sid(78170).agi=45;

idb.sid(78171).name='Dragonscale Leg Armor';
idb.sid(78171).ap=190;
idb.sid(78171).crit=55;

idb.sid(78172).name='Charscale Leg Armor';
idb.sid(78172).sta=145;
idb.sid(78172).agi=55;

idb.sid(101598).name='Drakehide Leg Armor';
idb.sid(101598).sta=145;
idb.sid(101598).dodge=55;

%% Feet
idb.sid(74189).name='Enchant Boots - Earthen Vitality';
idb.sid(74189).sta=30;

idb.sid(74252).name='Enchant Boots - Assassin''s Step';
idb.sid(74252).agi=25;

idb.sid(74253).name='Enchant Boots - Lavawalker';
idb.sid(74253).mast=35;

idb.sid(74213).name='Enchant Boots - Major Agility';
idb.sid(74213).agi=35;

idb.sid(74238).name='Enchant Boots - Mastery';
idb.sid(74238).mast=50;

idb.sid(74236).name='Enchant Boots - Precision';
idb.sid(74236).hit=50;

%% Rings
idb.sid(74218).name='Enchant Ring - Greater Stamina';
idb.sid(74218).sta=75;

idb.sid(74215).name='Enchant Ring - Strength';
idb.sid(74215).str=50;

%% Weapon
%LK enchants
idb.sid(59619).name='Enchant Weapon - Accuracy';
idb.sid(59619).hit=25;
idb.sid(59619).crit=25;

idb.sid(38995).name='Enchant Weapon - Exceptional Agility';
idb.sid(38995).agi=26;

idb.sid(60621).name='Enchant Weapon - Greater Potency';
idb.sid(60621).ap=50;

idb.sid(27972).name='Enchant Weapon - Potency';
idb.sid(27972).str=20;

idb.sid(41976).name='Titanium Weapon Chain';
idb.sid(41976).hit=28;

idb.sid(55057).name='Pyrium Weapon Chain';
idb.sid(55057).hit=40;


%Cata enchants
idb.sid(74195).name='Enchant Weapon - Mending';
idb.sid(74195).procid=74195;

idb.sid(74211).name='Enchant Weapon - Elemental Slayer';

idb.sid(74223).name='Enchant Weapon - Hurricane';
idb.sid(74223).procid=74223;

idb.sid(74242).name='Enchant Weapon - Power Torrent';
idb.sid(74242).procid=74242;

idb.sid(74244).name='Enchant Weapon - Windwalk';
idb.sid(74244).procid=74244;

idb.sid(74246).name='Enchant Weapon - Landslide';
idb.sid(74246).procid=74246;

idb.sid(74197).name='Enchant Weapon - Avalanche';
idb.sid(74197).procid=74197;

%% Shield
idb.sid(34009).name='Enchant Shield - Major Stamina';
idb.sid(34009).sta=18;

idb.sid(74207).name='Enchant Shield - Protection';
idb.sid(74207).earmor=160;

idb.sid(74226).name='Enchant Shield - Mastery';
idb.sid(74226).mast=50;


%% Consumables (invoked by buff_model)
% Flasks
idb.sid(79469).name='Flask of Steelskin';
idb.sid(79469).sta=450;

idb.sid(79472).name='Flask of Titanic Strength';
idb.sid(79472).str=300;

idb.sid(79471).name='Flask of the Winds';
idb.sid(79471).agi=300;

idb.sid(79470).name='Flask of the Draconic Mind';
idb.sid(79470).int=300;

% Battle Elixirs
idb.sid(79477).name='Elixir of the Cobra';
idb.sid(79477).crit=225;

idb.sid(79481).name='Elixir of Impossible Accuracy';
idb.sid(79481).hit=225;

idb.sid(79635).name='Elixir of the Master';
idb.sid(79635).mast=225;

% Guardian Elixirs
idb.sid(79474).name='Elixir of the Naga';
idb.sid(79474).exp=225;

idb.sid(79480).name='Elixir of Deep Earth';
idb.sid(79480).earmor=900;

% Potions
idb.sid(79475).name='Earthen Potion';
idb.sid(79475).earmor=4800;

idb.sid(79634).name='Golemblood Potion';
idb.sid(79634).str=1200;

% Food
idb.sid(87584).name='Beer-Basted Crocolisk';
idb.sid(87584).sta=90;
idb.sid(87584).str=90;

idb.sid(87594).name='Lavascale Minestrone';
idb.sid(87594).sta=90;
idb.sid(87594).mast=90;

idb.sid(87595).name='Grilled Dragon';
idb.sid(87595).sta=90;
idb.sid(87595).hit=90;

idb.sid(87597).name='Baked Rockfish';
idb.sid(87597).sta=90;
idb.sid(87597).crit=90;

idb.sid(87601).name='Mushroom Sauce Mudfish';
idb.sid(87601).sta=90;
idb.sid(87601).dodge=90;

idb.sid(87602).name='Blackbelly Sushi';
idb.sid(87602).sta=90;
idb.sid(87602).parry=90;

idb.sid(87637).name='Crocolisk Au Gratin';
idb.sid(87637).sta=90;
idb.sid(87637).exp=90;

idb.sid(62665).name='Basilisk Liverdog';
idb.sid(62665).sta=90;
idb.sid(62665).haste=90;

idb.sid(62669).name='Skewered Eel';
idb.sid(62669).sta=90;
idb.sid(62669).agi=90;

%% Gems (nota bene : mixt gems are counted twice, so a green one will be YB)
% Red
idb.iid(52206).name='Bold Inferno Ruby';
idb.iid(52206).str=40;
idb.iid(52206).socket='R';

idb.iid(52212).name='Delicate Inferno Ruby';
idb.iid(52212).agi=40;
idb.iid(52212).socket='R';

idb.iid(52216).name='Flashing Inferno Ruby';
idb.iid(52216).parry=40;
idb.iid(52216).socket='R';

idb.iid(52230).name='Precise Inferno Ruby';
idb.iid(52230).exp=40;
idb.iid(52230).socket='R';

idb.iid(52255).name='Bold Chimera''s Eye';
idb.iid(52255).str=67;
idb.iid(52255).socket='R';

idb.iid(52258).name='Delicate Chimera''s Eye';
idb.iid(52258).agi=67;
idb.iid(52258).socket='R';

idb.iid(52259).name='Flashing Chimera''s Eye';
idb.iid(52259).parry=67;
idb.iid(52259).socket='R';

idb.iid(52260).name='Precise Chimera''s Eye';
idb.iid(52260).exp=67;
idb.iid(52260).socket='R';

idb.iid(71883).name='Bold Queen''s Garnet';
idb.iid(71883).str=50;
idb.iid(71883).socket='R';

idb.iid(71879).name='Delicate Queen''s Garnet';
idb.iid(71879).agi=50;
idb.iid(71879).socket='R';

idb.iid(71882).name='Flashing Queen''s Garnet';
idb.iid(71882).parry=50;
idb.iid(71882).socket='R';

idb.iid(71880).name='Precise Queen''s Garnet';
idb.iid(71880).exp=50;
idb.iid(71880).socket='R';

% Orange
idb.iid(52204).name='Adept Ember Topaz';
idb.iid(52204).agi=20;
idb.iid(52204).mast=20;
idb.iid(52204).socket='RY';

idb.iid(52215).name='Fine Ember Topaz';
idb.iid(52215).parry=20;
idb.iid(52215).mast=20;
idb.iid(52215).socket='RY';

idb.iid(52222).name='Inscribed Ember Topaz';
idb.iid(52222).str=20;
idb.iid(52222).crit=20;
idb.iid(52222).socket='RY';

idb.iid(52224).name='Keen Ember Topaz';
idb.iid(52224).exp=20;
idb.iid(52224).mast=20;
idb.iid(52224).socket='RY';

idb.iid(52229).name='Polished Ember Topaz';
idb.iid(52229).agi=20;
idb.iid(52229).dodge=20;
idb.iid(52229).socket='RY';

idb.iid(52240).name='Skillful Ember Topaz';
idb.iid(52240).str=20;
idb.iid(52240).mast=20;
idb.iid(52240).socket='RY';

idb.iid(52249).name='Resolute Ember Topaz';
idb.iid(52249).exp=20;
idb.iid(52249).dodge=20;
idb.iid(52249).socket='RY';

idb.iid(71841).name='Crafty Lava Coral';
idb.iid(71841).exp=25;
idb.iid(71841).crit=25;
idb.iid(71841).socket='RY';

idb.iid(71855).name='Fine Lava Coral';
idb.iid(71855).parry=25;
idb.iid(71855).mast=25;
idb.iid(71855).socket='RY';

idb.iid(71843).name='Inscribed Lava Coral';
idb.iid(71843).str=25;
idb.iid(71843).crit=25;
idb.iid(71843).socket='RY';

idb.iid(71853).name='Keen Lava Coral';
idb.iid(71853).exp=25;
idb.iid(71853).mast=25;
idb.iid(71853).socket='RY';

idb.iid(71856).name='Skillful Lava Coral';
idb.iid(71856).str=25;
idb.iid(71856).mast=25;
idb.iid(71856).socket='RY';

% Yellow
idb.iid(52219).name='Fractured Amberjewel';
idb.iid(52219).mast=40;
idb.iid(52219).socket='Y';

idb.iid(52247).name='Subtle Amberjewel';
idb.iid(52247).dodge=40;
idb.iid(52247).socket='Y';

idb.iid(52265).name='Subtle Chimera''s Eye';
idb.iid(52265).dodge=67;
idb.iid(52265).socket='Y';

idb.iid(52269).name='Fractured Chimera''s Eye';
idb.iid(52269).mast=67;
idb.iid(52269).socket='Y';

idb.iid(71877).name='Fractured Lightstone';
idb.iid(71877).mast=50;
idb.iid(71877).socket='Y';

% Green
idb.iid(52227).name='Nimble Dream Emerald';
idb.iid(52227).dodge=20;
idb.iid(52227).hit=20;
idb.iid(52227).socket='YB';

idb.iid(52231).name='Puissant Dream Emerald';
idb.iid(52231).mast=20;
idb.iid(52231).sta=30;
idb.iid(52231).socket='YB';

idb.iid(52233).name='Regal Dream Emerald';
idb.iid(52233).dodge=20;
idb.iid(52233).sta=30;
idb.iid(52233).socket='YB';

idb.iid(52237).name='Sensei''s Dream Emerald';
idb.iid(52237).mast=20;
idb.iid(52237).hit=20;
idb.iid(52237).socket='YB';

idb.iid(71838).name='Puissant Elven Peridot';
idb.iid(71838).mast=25;
idb.iid(71838).sta=37;
idb.iid(71838).socket='YB';

idb.iid(71825).name='Sensei''s Elven Peridot';
idb.iid(71825).mast=25;
idb.iid(71825).hit=25;
idb.iid(71825).socket='YB';

% Blue
idb.iid(52235).name='Rigid Ocean Sapphire';
idb.iid(52235).hit=40;
idb.iid(52235).socket='B';

idb.iid(52242).name='Solid Ocean Sapphire';
idb.iid(52242).sta=60;
idb.iid(52242).socket='B';

idb.iid(52261).name='Solid Chimera''s Eye';
idb.iid(52261).sta=101;
idb.iid(52261).socket='B';

idb.iid(52264).name='Rigid Chimera''s Eye';
idb.iid(52264).hit=67;
idb.iid(52264).socket='B';

idb.iid(71817).name='Rigid Deepholm Iolite';
idb.iid(71817).hit=50;
idb.iid(71817).socket='B';

idb.iid(71820).name='Solid Deepholm Iolite';
idb.iid(71820).sta=75;
idb.iid(71820).socket='B';

% Purple
idb.iid(52203).name='Accurate Demonseye';
idb.iid(52203).exp=20;
idb.iid(52203).hit=20;
idb.iid(52203).socket='RB';

idb.iid(52210).name='Defender''s Demonseye';
idb.iid(52210).parry=20;
idb.iid(52210).sta=30;
idb.iid(52210).socket='RB';

idb.iid(52213).name='Etched Demonseye';
idb.iid(52213).str=20;
idb.iid(52213).hit=20;
idb.iid(52213).socket='RB';

idb.iid(52220).name='Glinting Demonseye';
idb.iid(52220).agi=20;
idb.iid(52220).hit=20;
idb.iid(52220).socket='RB';

idb.iid(52221).name='Guardian''s Demonseye';
idb.iid(52221).exp=20;
idb.iid(52221).sta=30;
idb.iid(52221).socket='RB';

idb.iid(52234).name='Retaliating Demonseye';
idb.iid(52234).parry=20;
idb.iid(52234).hit=20;
idb.iid(52234).socket='RB';

idb.iid(52238).name='Shifting Demonseye';
idb.iid(52238).agi=20;
idb.iid(52238).sta=30;
idb.iid(52238).socket='RB';

idb.iid(52243).name='Sovereign Demonseye';
idb.iid(52243).str=20;
idb.iid(52243).sta=30;
idb.iid(52243).socket='RB';

idb.iid(71863).name='Accurate Shadow Spinel';
idb.iid(71863).exp=25;
idb.iid(71863).hit=25;
idb.iid(71863).socket='RB';

idb.iid(71872).name='Defender''s Shadow Spinel';
idb.iid(71872).parry=25;
idb.iid(71872).sta=37;
idb.iid(71872).socket='RB';

idb.iid(71866).name='Etched Shadow Spinel';
idb.iid(71866).str=25;
idb.iid(71866).hit=25;
idb.iid(71866).socket='RB';

% Prismatic /TODO check for lvl85 homologue
idb.iid(49110).name='Nightmare Tear';
idb.iid(49110).str=10;
idb.iid(49110).sta=10;
idb.iid(49110).agi=10;
idb.iid(49110).socket='P';

% Meta
idb.iid(68779).name='Chaotic Shadowspirit Diamond';
idb.iid(68779).str=54;
idb.iid(68779).meta=3;
idb.iid(68779).socket='M';

idb.iid(52293).name='Eternal Shadowspirit Diamond';
idb.iid(52293).sta=81;
idb.iid(52293).meta=2;
idb.iid(52293).socket='M';

idb.iid(52294).name='Austere Shadowspirit Diamond';
idb.iid(52294).sta=81;
idb.iid(52294).meta=1;
idb.iid(52294).socket='M';

idb.iid(52295).name='Effulgent Shadowspirit Diamond';
idb.iid(52295).sta=81;
idb.iid(52295).meta=4;
idb.iid(52295).socket='M';

idb.iid(52299).name='Powerful Shadowspirit Diamond';
idb.iid(52299).sta=81;
idb.iid(52299).meta=5;
idb.iid(52299).socket='M';
