%% Gear
%This file serves as a master gear database.

%instructions on how to invoke gear here

%test of svn
%another test of svn
%yet another svn test
%tlitp was here


%% Contribution from gear
%Item stats are listed in an array format below.  The format is as follows:
%Item   = [STR STA AGI INT SPI Hit Crit Exp AP SP Haste ArP Def Dod Parr BV BR Armor]
%I've included a bunch of the basic stuff pre-loaded (T7 and T7.5, for
%example) so that users can just comment and uncomment large sections to
%compare gear.

%% Helm, Chest, Gloves, Legs, and Shoulders - split this way to make tier set
%swapping easier
global idb
% idb=struct( 'name','Broken Promise', ...
%             'type','ohw', ...
%             'ilvl',213, ...
%             'dps',156.6, ...
%             'speed',2.5, ...
%             'str',29, ...
%             'sta',64,...
%             'agi',0,...
%             'int',0,...
%             'spi',0,...
%             'hit',16,...
%             'crit',0,...
%             'exp',20,...
%             'haste',0,...
%             'mastery',0,...
%             'dodge',0,...
%             'parry',0,...
%             'block',0,...
%             'blval',0,...
%             'armor',0,...
%             'bonusarmor',0);
%         
% idb(10)=idb(1);


%% Alternate Method
idb.brokenpromise =struct('name','Broken Promise', ...
            'type','ohw', ...
            'ilvl',213, ...
            'dps',156.6, ...
            'speed',2.5, ...
            'str',29, ...
            'sta',64,...
            'agi',0,...
            'int',0,...
            'spi',0,...
            'hit',16,...
            'crit',0,...
            'exp',20,...
            'haste',0,...
            'mastery',0,...
            'dodge',0,...
            'parry',0,...
            'block',0,...
            'blval',0,...
            'armor',0,...
            'bonusarmor',0);

idb.tempitem=idb.brokenpromise;

%% Enchants
%Format:
%Item   = [STR STA AGI INT SPI Hit Crit Exp AP SP Haste ArP Def Dod Parr BV BR Armor]
HelmEnch= [37    0  0   0   0   0   0    0   0  0   0    0   20   0   0   0  0     0];
ShouEnch= [0     0  0   0   0   0   0    0   0  0   0    0   15  20   0   0  0     0];
BackEnch= [0     0  0   0   0   0   0    0   0  0   0    0   16   0   0   0  0     0];
ChesEnch= [0     0  0   0   0   0   0    0   0  0   0    0   22   0   0   0  0     0];
BracEnch= [0    40  0   0   0   0   0    0   0  0   0    0    0   0   0   0  0     0];
GlovEnch= [0     0  0   0   0   0   0    0   0  0   0    0    0   0  10   0  0     0]; %armsman
BeltEnch= [0     0  0   0   0   0   0    0   0  0   0    0    0   0   0   0  0     0]; %placeholder for future useful tinkers
LegsEnch= [0    55 22   0   0   0   0    0   0  0   0    0    0   0   0   0  0     0];
BootEnch= [0    15  0   0   0   0   0    0   0  0   0    0    0   0   0   0  0     0];
Rin1Ench= [0     0  0   0   0   0   0    0   0  0   0    0    0   0   0   0  0     0];
Rin2Ench= [0     0  0   0   0   0   0    0   0  0   0    0    0   0   0   0  0     0];
WeapEnch= [ 0    0  0   0   0  25  25    0   0  0   0    0    0   0   0   0  0     0];
ShieEnch= [0     0  0   0   0   0   0    0   0  0   0    0   20   0   0   0  0     0];



