%prio_model sets up the basic priority queue structures that are then
%executed by the priority simulator module.

%define base cooldowns - this section may be moved to ability recalc
cd.CS=4.5;cd.Jud=8;cd.AS=15;cd.HoWr=15;cd.Cons=30;


prio(1).name='Sample FCFS';
prio(1).labels={'3ShoR';'CS';'Jud';'AS';'HoWr';'Cons'};
prio(1).cds=[0 cd.CS cd.Jud cd.AS cd.HoWr cd.Cons];
%define gcd lengths
prio(1).gcds=[1.5 1.5 1.5 1.5 player.spgcd player.spgcd];
prio(1).ids=[1 2 3 4 5 6];  %id numbers for generating figures
prio(1).castname={'ShieldoftheRighteous'; ...
                  'CrusaderStrike'; ...
                  'Judgement';...
                  'AvengersShield';...
                  'HolyWrath';...
                  'Consecration'};
              
%damage values, would rather have this in prio_sim but I'm undecided on
%what would be better
prio(1).dmg=[dmg.ShieldoftheRighteous; ...
             dmg.CrusaderStrike;...
             dmg.Judgement;...
             dmg.AvengersShield;...
             dmg.HolyWrath;...
             dmg.Consecration];

         
%action is the structure that contains post-cast actions, including
%resetting spell cooldowns
prio(1).action={'hopo=0;sdflag=0;dur.SD=0;';...
                'ccd.CS=cd.CS;hopo=min([3 hopo+1]);if rand<mdf.GC ccd.AS=0; end;';...
                'ccd.Jud=cd.Jud;if rand<mdf.SacDut dur.SD=15; end;';...
                'ccd.AS=cd.AS;';...
                'ccd.HoWr=cd.HoWr;';...
                'ccd.Cons=cd.Cons;'};
          
%setup contains commands to be evaluated at the beginning of the
%simulation.  For example, setting ccd.AS=13.5 would simulate pulling with
%AS, making it unavailable early on in the queue.
prio(1).setup={'ccd.AS=13.5;'};

%cond is the structure that contains the conditionals which will be
%evaluated.  Each string should give a logical 1 or 0 when evaluated.
prio(1).cond={'hopo>=3 && ccd.CS>1.5 && ccd.Jud<=0 && dur.SD<=0';...
              'hopo>=3';...
              'ccd.CS<=0';...
              'ccd.Jud<=0';...
              'ccd.AS<=0';...
              'ccd.HoWr<=0'; ...
              'ccd.Cons<=0'};

%cast is the index of the spell that will be cast if the conditional is true
prio(1).cast=[3;1;2;3;4;5;6];

%spaction is the structure that contains any special actions that should
%occur for specific conditions.  It is run after all of the default actions
%defined in prio.action
prio(1).spaction={'';''; ''; ''; ''; ''; ''; '';};


