%ROTATION_COEFF_FIT takes a set of rcgd.coeff data generated by
%rotation_coeff_data and fits each data set with a 5th-order polynomial.
%The results are stored in rcgd.pvals

%% Now for fits/plots
%we do this for each line of rcgd.coeff
for a=1:size(rcgd.coeff,1);rcgd.ftype{a}='poly5';end
rcgd.ftype{3}='poly2';
rcgd.ftype{11}='poly4';

rcgd.maxlength=1;
for a=1:size(rcgd.coeff,1)
    
    %fit coeffs
    x=[];y=[];
    for m=1:M
        x=[x h];
        y=[y rcgd.coeff(a,:,m)'];
    end
    rcgd.coeffcf{a}=fit(x(:),y(:),fittype(rcgd.ftype{a})); %fit data
    
    rcgd.maxlength=max([rcgd.maxlength length(coeffvalues(rcgd.coeffcf{a}))]);

    if rcgd.showplots==1
        figure(a)
        plot(x,y,'.-',h,feval(rcgd.cf.coeff{a},h),'ko-');
        title(char(priolist(a).alabel))
        xlabel('mdf.mehit (h)')
        ylabel('rcgd.coeff and fit')
    end
    
    %fit cps
    clear x y
    x=[];y=[];
    for m=1:M
        x=[x h];
        y=[y rcgd.cps(a,:,m)'];
    end
    rcgd.cpscf{a}=fit(x(:),y(:),fittype(rcgd.ftype{a})); %fit data
    
end

%% Collect and store coefficients
rcgd.coeffpvals=zeros(size(rcgd.coeff,1),rcgd.maxlength);
rcgd.cpspvals=rcgd.coeffpvals;
for a=1:size(rcgd.coeff,1)
    rcgd.tmp=coeffvalues(rcgd.coeffcf{a});
    rcgd.coeffpvals(a,1+size(rcgd.coeffpvals,2)-length(rcgd.tmp):size(rcgd.coeffpvals,2))=rcgd.tmp;
    rcgd.tmp=coeffvalues(rcgd.cpscf{a});
    rcgd.cpspvals(a,1+size(rcgd.coeffpvals,2)-length(rcgd.tmp):size(rcgd.coeffpvals,2))=rcgd.tmp;
end

% rcgd.pvals
