%ROTATION_COEFF_FIT takes a set of rcgd.coeff data generated by
%rotation_coeff_data and fits each data set with a 5th-order polynomial.
%The results are stored in rcgd.pvals

%% Now for fits/plots
%we do this for each line of rcgd.coeff
for a=1:size(rcgd.coeff,1);rcgd.ftype{a}='poly5';end
rcgd.ftype{3}='poly2';
rcgd.ftype{11}='poly4';

rcgd.maxlength=1;
for a=1:size(rcgd.coeff,1)
    
    x=[];y=[];
    for m=1:M
        x=[x h];
        y=[y rcgd.coeff(a,:,m)'];
    end
    rcgd.cf{a}=fit(x(:),y(:),fittype(rcgd.ftype{a})); %fit data
    
    rcgd.maxlength=max([rcgd.maxlength length(coeffvalues(rcgd.cf{a}))]);

    if rcgd.showplots==1
        figure(a)
        plot(x,y,'.-',h,feval(rcgd.cf{a},h),'ko-');
        title(char(priolist(a).alabel))
        xlabel('mdf.mehit (h)')
        ylabel('rcgd.coeff and fit')
    end
end

%% Collect and store coefficients
rcgd.pvals=zeros(size(rcgd.coeff,1),rcgd.maxlength);
for a=1:size(rcgd.coeff,1)
    rcgd.tmp=coeffvalues(rcgd.cf{a});
    rcgd.pvals(a,1:length(rcgd.tmp))=rcgd.tmp;
end

% rcgd.pvals
