%ROTATION_COEFF_FIT takes a set of rdbgen.coeff data generated by
%rotation_coeff_data and fits each data set with a 5th-order polynomial.
%The results are stored in rdbgen.pvals

%% Now for fits/plots
%we do this for each line of rdbgen.coeff
for a=1:size(rdbdata.coeff,1);rdbfit.ftype{a}='poly5';end
rdbfit.ftype{3}='poly2';
rdbfit.ftype{11}='poly4';

rdbfit.maxlength=1;
for a=1:size(rdbdata.coeff,1)
    
    %fit coeffs
    x=[];y=[];
    for m=1:M
        x=[x h];
        y=[y rdbdata.coeff(a,:,m)'];
    end
    rdbfit.coeff{a}=fit(x(:),y(:),fittype(rdbfit.ftype{a})); %fit data
    
    rdbfit.maxlength=max([rdbfit.maxlength length(coeffvalues(rdbfit.coeff{a}))]);

    if rdbgen.showplots==1  %TODO: add exist/field check
        figure(a)
        plot(x,y,'.-',h,feval(rdbfit.coeff{a},h),'ko-');
        title(char(priolist(a).alabel))
        xlabel('mdf.mehit (h)')
        ylabel('rdbgen.coeff and fit')
    end
    
    %fit cps
    clear x y
    x=[];y=[];
    for m=1:M
        x=[x h];
        y=[y rdbdata.cps(a,:,m)'];
    end
    rdbfit.cps{a}=fit(x(:),y(:),fittype(rdbfit.ftype{a})); %fit data
    
end
    
%fit Inq
clear x y
x=repmat(h,1,M);
y=squeeze(rdbdata.inqup(1,:,:));
rdbfit.inq=fit(x(:),y(:),fittype('poly5')); %fit data

%% Collect and store coefficients
rdbfit.coeffpvals=zeros(size(rdbdata.coeff,1),rdbfit.maxlength);
rdbfit.cpspvals=zeros(size(rdbdata.cps,1),rdbfit.maxlength);
rdbfit.inqpvals=zeros(1,rdbfit.maxlength);
for a=1:size(rdbdata.coeff,1)
    rdbfit.tmp=coeffvalues(rdbfit.coeff{a});
    rdbfit.coeffpvals(a,1+size(rdbfit.coeffpvals,2)-length(rdbfit.tmp):size(rdbfit.coeffpvals,2))=rdbfit.tmp;
    rdbfit.tmp=coeffvalues(rdbfit.cps{a});
    rdbfit.cpspvals(a,1+size(rdbfit.coeffpvals,2)-length(rdbfit.tmp):size(rdbfit.cpspvals,2))=rdbfit.tmp;
end
rdbfit.tmp=coeffvalues(rdbfit.inq);
rdbfit.inqpvals(1,1+size(rdbfit.inqpvals,2)-length(rdbfit.tmp):size(rdbfit.inqpvals,2))=rdbfit.tmp;

% rdbgen.pvals
