function [fitresult, gof] = dodgeSurfaceFit(baseAgi, bonusAgi, preDodge, postDodge)
%CREATESURFACEFIT1(BONUSSTR,PREPARRY,POSTPARRY)
%  Fit surface to data.
%
%  Data for 'untitled fit 1' fit:
%      X Input : bonusStr
%      Y Input : preParry
%      Z Output: postParry
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2012 15:15:46


%% Fit: 'untitled fit 1'.
[xInput, yInput, zOutput] = prepareSurfaceData( bonusAgi, preDodge, postDodge);
fitType=['3+' int2str(baseAgi) '/951.158596+(x/951.158596+y)/((x/951.158596+y)/C+k)'];

% Set up fittype and options.
ft = fittype( fitType , 'indep', {'x', 'y'}, 'depend', 'z' );
opts = fitoptions( ft );
opts.DiffMinChange = 1e-012;
opts.Display = 'Off';
opts.Lower = [480 1.3];
opts.MaxFunEvals = 60000;
opts.MaxIter = 40000;
opts.Robust = 'Bisquare';
opts.StartPoint = [499.1 1.422];
opts.TolFun = 1e-012;
opts.TolX = 1e-012;
opts.Upper = [520 1.5];

% Fit model to data.
[fitresult, gof] = fit( [xInput, yInput], zOutput, ft, opts );

% Create a figure for the plots.
figure( 1 );

% Plot fit with data.
h = plot( fitresult, [xInput, yInput], zOutput );
legend( h, 'untitled fit 1', 'postParry vs. bonusStr, preParry', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusAgi' );
ylabel( 'dodgeRating' );
zlabel( 'postDodge' );
grid on

% Plot residuals.
figure(2)
h = plot( fitresult, [xInput, yInput], zOutput, 'Style', 'Residual' );
legend( h, 'untitled fit 1 - residuals', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusAgi' );
ylabel( 'dodgeRating' );
zlabel( 'postDodge' );
grid on
view( -57.5, 56 );


