function import_tmi_xlsx(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 24-Mar-2014 14:58:56

if nargin<1
    fileToRead1='tmi_beta_test_export.xlsx';
    warning('No import file provided, using default!!')
end


% Import the file
sheetName='Sheet 1';
[numbers, strings] = xlsread(fileToRead1, sheetName);

% create arrays from numeric data
if ~isempty(numbers)
    data.rawdata =  numbers;
    data.window = numbers(:,1);
    data.ilvl = numbers(:,2);
    data.tmi = numbers(:,3);
    data.tmi_error = numbers(:,4);
    
    stats={'str';'agi';'sta';'exp';'hit';'crit';'haste';'mast';'armor';'dodge';'parry'};
    for i=1:length(stats)
       data.(stats{i})=numbers(:,i+4); 
    end
end

%create arrays from text data
s=2:(size(strings,1)-1);
if ~isempty(strings)
    data.textdata =  strings;
    data.names = strings(s,1);
    data.servers = strings(s,2);
    data.class = strings(s,3);
    data.boss = strings(s,4);
end

% Create new variables in the base workspace from those fields.
vars = fieldnames(data);
for i = 1:length(vars)
    assignin('base', vars{i}, data.(vars{i}));
end

