function util_import_CSV(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 14-Feb-2014 13:33:10

% Import the file
rawData = importdata(fileToRead1);


newData.N=rawData(:,1);
newData.sampleMean=rawData(:,2);
newData.sampleError=rawData(:,3);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData);
for i = 1:length(vars)
    assignin('base', vars{i}, newData.(vars{i}));
end

