function [fitresult, gof] = dodgeSurfaceFit( set, base )
% DODGESURFACEFIT(SET, BASE)
%  Input:
%      set : a data set structure generated by parseChatLog
%      base : structure containing base stat information
%
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2012 15:15:46

%% unpack data set
baseAgi = base.agi;
baseDodge = base.dodge;
bonusAgi = set.agi - base.agi;
preDodge = set.preDodge;
postDodge = set.postDodge;
a2d = base.agi2dodge;
vs = base.vs;
df = base.df;
hs = base.hs;
nondrAgi=0;

%In WoD, race agility is magically being added twice. It's giving some
%dodge that is not affected by DR, but is also being included in
%bonusDodge.
nondrAgi = base.raceAgi;
bonusAgi = bonusAgi-nondrAgi;

bonusDodge = bonusAgi*a2d+preDodge;
    
%% Fit: 'untitled fit 1'.
xInput = bonusDodge; 
zOutput = postDodge;

fitType=[ int2str(baseDodge) '+(' int2str(nondrAgi) '+R)*' num2str(a2d) '+x/(x*' num2str(df) '*vs+hs)'];

%bounds on HS/VS
deltaQ=10;
deltaHS=0.00001;
deltaVS=0.000001;

% Set up fittype and options.
ft = fittype( fitType , 'indep', 'x', 'depend', 'z' );
opts = fitoptions( ft );
opts.DiffMinChange = 1e-012;
opts.Display = 'Off';
opts.Lower = [ -deltaQ hs-deltaHS vs-deltaVS];
opts.MaxFunEvals = 60000;
opts.MaxIter = 40000;
opts.Robust = 'Bisquare';
opts.StartPoint = [ 0 hs vs];
opts.TolFun = 1e-012;
opts.TolX = 1e-012;
opts.Upper = [ deltaQ hs+deltaHS vs+deltaVS];

% Fit model to data.
[fitresult, gof] = fit( xInput, zOutput, ft, opts );
residuals = fitresult(xInput)-zOutput;

% Create a figure for the plots.
figure( 1 );

% Plot fit with data.
h = plot( fitresult, xInput, zOutput );
legend( h, 'fit', 'postDodge vs. bonusDodge', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusDodge' );
ylabel( 'postDodge' );
grid on

% Plot residuals.
figure(2)
plot(xInput, residuals, 'o-',  xInput, zeros(size(xInput)),'k-' );
legend('fit residuals', 'Location', 'Best' );
% Label axes
xlabel( 'bonusDodge' );
zlabel( 'fit - postDodge' );
grid on


disp('==== Dodge Curve Fit=====')


if sum(bonusDodge==0)==length(bonusDodge)
    warning('---------------No bonusDodge to fit-------------------')
end
% fitresult
% %% 
% [fitresult(xInput) zOutput fitresult(xInput)-zOutput]
%  num2str(coeffvalues(fitresult)','%1.10f')
 end

