function [fitresult, gof] = parrySurfaceFit( set, base )
% DODGESURFACEFIT(SET, BASE)
%  Input:
%      set : a data set structure generated by parseChatLog
%      base : structure containing base stat information
%
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2012 15:15:46

%% unpack data set
baseStr = base.str;
baseParry = base.parry;
bonusStr = set.str - base.str;
preParry = set.preParry;
postParry = set.postParry;
s2p = base.str2parry;

%% Fit: 'untitled fit 1'.
[xInput, yInput, zOutput] = prepareSurfaceData( bonusStr, preParry, postParry);
fitType=[ int2str(baseParry) '+' int2str(baseStr) '/' num2str(s2p,'%f') '+(x/' num2str(s2p,'%f') '+y)/((x/' num2str(s2p,'%f') '+y)/C+k)'];

% Set up fittype and options.
ft = fittype( fitType , 'indep', {'x', 'y'}, 'depend', 'z' );
opts = fitoptions( ft );
opts.DiffMinChange = 1e-012;
opts.Display = 'Off';
opts.Lower = [20 0.8];
opts.MaxFunEvals = 60000;
opts.MaxIter = 40000;
opts.Robust = 'Bisquare';
opts.StartPoint = [499.1 1.422];
opts.TolFun = 1e-012;
opts.TolX = 1e-012;
opts.Upper = [520 1.5];

% Fit model to data.
[fitresult, gof] = fit( [xInput, yInput], zOutput, ft, opts );

% Create a figure for the plots.
figure( 3 );

% Plot fit with data.
h = plot( fitresult, [xInput, yInput], zOutput );
legend( h, 'fit', 'postParry vs. bonusStr, preParry', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusStr' );
ylabel( 'preParry' );
zlabel( 'postParry' );
grid on

% Plot residuals.
figure(4)
h = plot( fitresult, [xInput, yInput], zOutput, 'Style', 'Residual' );
legend( h, 'fit residuals', 'Location', 'NorthEast' );
% Label axes
xlabel( 'bonusStr' );
ylabel( 'preParry' );
zlabel( 'postParry' );
grid on
view( -57.5, 56 );


